from pathlib import Path

p = Path('Halo/Views/DecorationsView.swift')
text = p.read_text()

def once(old, new):
    global text
    if old not in text:
        raise SystemExit(f'missing anchor: {old[:160]!r}')
    text = text.replace(old, new, 1)

# Add a distinct seasonal hanging decoration without forcing seasonal mode.
once('''    case hangingStars = "Hanging Stars / Moons"\n    case icicles = "Icicles"\n''', '''    case hangingStars = "Hanging Stars / Moons"\n    case christmasOrnaments = "Christmas Ornaments"\n    case icicles = "Icicles"\n''')
once('''        case .fairyLights, .hangingStars, .icicles: return .hanging\n''', '''        case .fairyLights, .hangingStars, .christmasOrnaments, .icicles: return .hanging\n''')
once('''        case .hangingStars: return "sparkles"\n        case .icicles: return "triangle.fill"\n''', '''        case .hangingStars: return "sparkles"\n        case .christmasOrnaments: return "circle.grid.cross"\n        case .icicles: return "triangle.fill"\n''')
once('''        case .hangingStars: return [.count, .spacing, .length, .bloom, .sway, .cursor, .symmetry]\n        case .icicles: return [.count, .spacing, .length, .density, .bloom, .symmetry]\n''', '''        case .hangingStars: return [.count, .spacing, .length, .bloom, .sway, .cursor, .symmetry]\n        case .christmasOrnaments: return [.count, .spacing, .length, .bloom, .sway, .cursor, .symmetry]\n        case .icicles: return [.count, .spacing, .length, .density, .bloom, .symmetry]\n''')

# Placement is now a real transform of the procedural attachment frame.
once('''            let notch = CGRect(x: (size.width - notchWidth) / 2, y: 0, width: notchWidth, height: notchHeight)\n            NotchAmbientPainter.draw(kind: settings.decoration, context: &context, size: size, notch: notch,\n                                     settings: settings, phase: phase, audio: audio, cursor: cursor,\n                                     palette: palette, lowPower: lowPower, date: date)\n            if let season = settings.resolvedSeason(at: date) {\n                NotchAmbientPainter.drawSeason(season, context: &context, size: size, notch: notch,\n''', '''            let physicalNotch = CGRect(x: (size.width - notchWidth) / 2, y: 0, width: notchWidth, height: notchHeight)\n            let artworkNotch = NotchAmbientPainter.placedNotch(physicalNotch, settings: settings)\n            NotchAmbientPainter.draw(kind: settings.decoration, context: &context, size: size, notch: artworkNotch,\n                                     settings: settings, phase: phase, audio: audio, cursor: cursor,\n                                     palette: palette, lowPower: lowPower, date: date)\n            if let season = settings.resolvedSeason(at: date) {\n                NotchAmbientPainter.drawSeason(season, context: &context, size: size, notch: physicalNotch,\n''')

# Cursor smoothing changes the falloff curve instead of being a dead control.
once('''        let d = max(1, hypot(dx, dy)); let radius = CGFloat(settings.reactionRadius)\n        guard d < radius else { return (0, 0, 0) }\n        let strength = Double(1 - d / radius) * settings.reactionStrength\n''', '''        let d = max(1, hypot(dx, dy)); let radius = CGFloat(settings.reactionRadius)\n        guard d < radius else { return (0, 0, 0) }\n        let raw = Double(1 - d / radius)\n        let exponent = max(0.35, 1.85 - settings.reactionSmoothing * 1.45)\n        let strength = pow(raw, exponent) * settings.reactionStrength\n''')

# Introduce placement helper and pass cursor into edge/halo rendering.
once('''    static func draw(kind: NotchAmbientDecorationKind, context: inout GraphicsContext, size: CGSize, notch: CGRect,\n''', '''    static func placedNotch(_ notch: CGRect, settings s: NotchAmbientSettings) -> CGRect {\n        switch s.placement {\n        case .above: return notch.offsetBy(dx: 0, dy: -min(10, notch.height * 0.25))\n        case .below: return notch.offsetBy(dx: 0, dy: min(18, notch.height * 0.45))\n        case .left: return notch.offsetBy(dx: -min(54, notch.width * 0.28), dy: 0)\n        case .right: return notch.offsetBy(dx: min(54, notch.width * 0.28), dy: 0)\n        case .around, .behind, .edgeAttached: return notch\n        }\n    }\n\n    static func draw(kind: NotchAmbientDecorationKind, context: inout GraphicsContext, size: CGSize, notch: CGRect,\n''')
once('''        case .edgeGlow: drawEdgeGlow(&context, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette)\n        case .halo: drawHalo(&context, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette)\n''', '''        case .edgeGlow: drawEdgeGlow(&context, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, cursor: cursor)\n        case .halo: drawHalo(&context, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, cursor: cursor)\n''')
once('''        case .fairyLights: drawHanging(&context, size: size, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, stars: false, cursor: cursor, lowPower: lowPower)\n        case .hangingStars: drawHanging(&context, size: size, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, stars: true, cursor: cursor, lowPower: lowPower)\n        case .icicles: drawIcicles(&context, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, lowPower: lowPower)\n''', '''        case .fairyLights: drawHanging(&context, size: size, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, stars: false, ornaments: false, cursor: cursor, lowPower: lowPower)\n        case .hangingStars: drawHanging(&context, size: size, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, stars: true, ornaments: false, cursor: cursor, lowPower: lowPower)\n        case .christmasOrnaments: drawHanging(&context, size: size, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, stars: false, ornaments: true, cursor: cursor, lowPower: lowPower)\n        case .icicles: drawIcicles(&context, notch: notch, s: s, phase: phase, intensity: intensity, palette: palette, lowPower: lowPower)\n''')

# Falloff and cursor reaction visibly affect minimal glow/halo.
once('''    private static func drawEdgeGlow(_ ctx: inout GraphicsContext, notch n: CGRect, s: NotchAmbientSettings, phase: Double, intensity: Double, palette: [Color]) {\n        let breathe = 1 + sin(phase * 0.75) * s.pulse * 0.22\n        let y = n.maxY + 0.5\n        let points = [CGPoint(x: n.minX, y: n.minY + n.height * 0.46), CGPoint(x: n.minX, y: y), CGPoint(x: n.maxX, y: y), CGPoint(x: n.maxX, y: n.minY + n.height * 0.46)]\n        glowLine(&ctx, points, color: c(palette, 0).opacity(intensity * breathe), width: CGFloat(s.thickness), bloom: s.softness / 22)\n''', '''    private static func drawEdgeGlow(_ ctx: inout GraphicsContext, notch n: CGRect, s: NotchAmbientSettings, phase: Double, intensity: Double, palette: [Color], cursor: CGPoint?) {\n        let breathe = 1 + sin(phase * 0.75) * s.pulse * 0.22\n        let y = n.maxY + 0.5\n        let falloff = 0.52 + s.falloff * 0.48\n        let points = [CGPoint(x: n.minX, y: n.minY + n.height * 0.46), CGPoint(x: n.minX, y: y), CGPoint(x: n.maxX, y: y), CGPoint(x: n.maxX, y: n.minY + n.height * 0.46)]\n        glowLine(&ctx, points, color: c(palette, 0).opacity(intensity * breathe * falloff), width: CGFloat(s.thickness), bloom: s.softness / 22)\n        if let cursor {\n            let x = min(n.maxX, max(n.minX, cursor.x))\n            let anchor = CGPoint(x: x, y: y)\n            let reaction = cursorInfluence(cursor, point: anchor, settings: s)\n            if reaction.strength > 0 {\n                let half = CGFloat(12 + reaction.strength * 22)\n                glowLine(&ctx, [CGPoint(x:max(n.minX,x-half),y:y), CGPoint(x:min(n.maxX,x+half),y:y)], color:c(palette,1).opacity(intensity*(0.35+reaction.strength)), width:CGFloat(s.thickness*1.15), bloom:min(1,s.softness/18))\n            }\n        }\n''')
once('''    private static func drawHalo(_ ctx: inout GraphicsContext, notch n: CGRect, s: NotchAmbientSettings, phase: Double, intensity: Double, palette: [Color]) {\n        let p = 1 + sin(phase * 0.55) * s.pulse * 0.18\n''', '''    private static func drawHalo(_ ctx: inout GraphicsContext, notch n: CGRect, s: NotchAmbientSettings, phase: Double, intensity: Double, palette: [Color], cursor: CGPoint?) {\n        let interaction = cursorInfluence(cursor, point: CGPoint(x:n.midX,y:n.maxY), settings:s).strength\n        let p = 1 + sin(phase * 0.55) * s.pulse * 0.18 + interaction * 0.08\n        let falloff = 0.52 + s.falloff * 0.48\n''')
once('''            ellipse(&ctx, rect: rect, color: c(palette, i).opacity(intensity * (0.18 - Double(i) * 0.025)), fill: false, width: CGFloat(5 + i * 3))\n''', '''            ellipse(&ctx, rect: rect, color: c(palette, i).opacity(intensity * falloff * (0.18 - Double(i) * 0.025) * (1 + interaction)), fill: false, width: CGFloat(5 + i * 3))\n''')

# Hanging spacing, moon silhouettes and ornaments are all distinct render paths.
once('''    private static func drawHanging(_ ctx: inout GraphicsContext, size: CGSize, notch n: CGRect, s: NotchAmbientSettings, phase: Double, intensity: Double, palette: [Color], stars: Bool, cursor: CGPoint?, lowPower: Bool) {\n        let count = max(2, min(lowPower ? 12 : 24, s.count)); let span = n.width * 0.88\n''', '''    private static func drawHanging(_ ctx: inout GraphicsContext, size: CGSize, notch n: CGRect, s: NotchAmbientSettings, phase: Double, intensity: Double, palette: [Color], stars: Bool, ornaments: Bool, cursor: CGPoint?, lowPower: Bool) {\n        let count = max(2, min(lowPower ? 12 : 24, s.count)); let span = n.width * CGFloat(min(1.35, max(0.55, 0.55 + s.spacing * 0.33)))\n''')
once('''            if stars {\n                let r = CGFloat(2.5 + rand(i, seed: s.seed, salt: 14)*2.2)\n                line(&ctx, [CGPoint(x:end.x-r,y:end.y), CGPoint(x:end.x+r,y:end.y)], color: color, width: 1)\n                line(&ctx, [CGPoint(x:end.x,y:end.y-r), CGPoint(x:end.x,y:end.y+r)], color: color, width: 1)\n                ellipse(&ctx, rect: CGRect(x:end.x-1.2,y:end.y-1.2,width:2.4,height:2.4), color: color, fill: true)\n            } else {\n''', '''            if stars {\n                let r = CGFloat(2.5 + rand(i, seed: s.seed, salt: 14)*2.2)\n                if i.isMultiple(of: 3) {\n                    var moon = Path(); moon.move(to:CGPoint(x:end.x,y:end.y-r-1)); moon.addCurve(to:CGPoint(x:end.x,y:end.y+r+1),control1:CGPoint(x:end.x-r*1.4,y:end.y-r*0.25),control2:CGPoint(x:end.x-r*1.4,y:end.y+r*0.35)); moon.addCurve(to:CGPoint(x:end.x,y:end.y-r-1),control1:CGPoint(x:end.x-r*0.10,y:end.y+r*0.30),control2:CGPoint(x:end.x-r*0.10,y:end.y-r*0.28)); moon.closeSubpath(); ctx.fill(moon,with:.color(color))\n                } else {\n                    line(&ctx, [CGPoint(x:end.x-r,y:end.y), CGPoint(x:end.x+r,y:end.y)], color: color, width: 1)\n                    line(&ctx, [CGPoint(x:end.x,y:end.y-r), CGPoint(x:end.x,y:end.y+r)], color: color, width: 1)\n                    ellipse(&ctx, rect: CGRect(x:end.x-1.2,y:end.y-1.2,width:2.4,height:2.4), color: color, fill: true)\n                }\n            } else if ornaments {\n                let radius=CGFloat(3.2+rand(i,seed:s.seed,salt:16)*2.1)\n                line(&ctx,[CGPoint(x:end.x,y:end.y-radius-3),CGPoint(x:end.x,y:end.y-radius)],color:Color.white.opacity(0.28+intensity*0.25),width:0.7)\n                ellipse(&ctx,rect:CGRect(x:end.x-radius,y:end.y-radius,width:radius*2,height:radius*2),color:c(palette,i).opacity(0.42+intensity*0.48),fill:true)\n                line(&ctx,[CGPoint(x:end.x-radius*0.45,y:end.y-radius*0.45),CGPoint(x:end.x+radius*0.35,y:end.y+radius*0.35)],color:Color.white.opacity(0.22),width:0.65)\n            } else {\n''')

# Moss bends near the cursor just like other foliage.
once('''            for i in 0..<count { let side = i.isMultiple(of:2) ? n.minX : n.maxX; let spread=CGFloat(rand(i,seed:s.seed,salt:31)*30); let x=side + (i.isMultiple(of:2) ? -spread:spread); let h=CGFloat(4+rand(i,seed:s.seed,salt:32)*18*s.density); line(&ctx,[CGPoint(x:x,y:n.maxY+2),CGPoint(x:x+CGFloat(sin(phase+Double(i)))*1.8*s.sway,y:n.maxY-h)],color:c(palette,i).opacity(0.32+intensity*0.45),width:1.1) }\n''', '''            for i in 0..<count { let side = i.isMultiple(of:2) ? n.minX : n.maxX; let spread=CGFloat(rand(i,seed:s.seed,salt:31)*30); let x=side + (i.isMultiple(of:2) ? -spread:spread); let h=CGFloat(4+rand(i,seed:s.seed,salt:32)*18*s.density); let tip=CGPoint(x:x+CGFloat(sin(phase+Double(i)))*1.8*s.sway,y:n.maxY-h); let react=cursorInfluence(cursor,point:tip,settings:s); line(&ctx,[CGPoint(x:x,y:n.maxY+2),CGPoint(x:tip.x+react.dx,y:tip.y+react.dy)],color:c(palette,i).opacity(0.32+intensity*0.45),width:1.1) }\n''')

# Portal reacts to pointer proximity by energizing the rings/escaped particles.
once('''        case .portal:\n            let center=CGPoint(x:n.midX,y:n.midY+5)\n            for i in 0..<7 { let pad=CGFloat(7+i*7); ellipse(&ctx,rect:CGRect(x:center.x-n.width/2-pad,y:center.y-CGFloat(13+i*2),width:n.width+pad*2,height:CGFloat(26+i*4)),color:c(palette,i).opacity(intensity*(0.25-Double(i)*0.022)),fill:false,width:CGFloat(1.2+(i%2))) }\n''', '''        case .portal:\n            let center=CGPoint(x:n.midX,y:n.midY+5)\n            let interaction=cursorInfluence(cursor,point:center,settings:s).strength\n            for i in 0..<7 { let pad=CGFloat(7+i*7); ellipse(&ctx,rect:CGRect(x:center.x-n.width/2-pad,y:center.y-CGFloat(13+i*2),width:n.width+pad*2,height:CGFloat(26+i*4)),color:c(palette,i).opacity(intensity*(0.25-Double(i)*0.022)*(1+interaction*1.3)),fill:false,width:CGFloat(1.2+(i%2))) }\n''')
once('''                let x=center.x+cos(a)*r; let y=center.y+sin(a)*r*0.36+CGFloat((phase*9+Double(i)*7).truncatingRemainder(dividingBy:18)); ellipse(&ctx,rect:CGRect(x:x-1,y:y-1,width:2,height:2),color:c(palette,i).opacity(intensity*0.58),fill:true) }\n''', '''                let x=center.x+cos(a)*r; let y=center.y+sin(a)*r*0.36+CGFloat((phase*(9+interaction*6)+Double(i)*7).truncatingRemainder(dividingBy:18)); ellipse(&ctx,rect:CGRect(x:x-1,y:y-1,width:2,height:2),color:c(palette,i).opacity(intensity*(0.58+interaction*0.32)),fill:true) }\n''')

p.write_text(text)
print('Notch Ambient interaction polish applied')
