from pathlib import Path
p = Path('Halo/Core/WidgetModels.swift')
s = p.read_text()
old = '''        case .capture:\n            return [\n                .init("hint", "Permission hint", "Screen Recording permission guidance."),\n                .init("actions", "Capture actions", "Capture region and OCR image actions."),\n                .init("progress", "Busy indicator", "Progress while capture/OCR is running."),\n                .init("result", "OCR result", "Recognized text."),\n                .init("resultActions", "Result actions", "Copy or clear recognized text."),\n                .init("status", "Capture status", "Errors and capture status.")\n            ]'''
new = '''        case .capture:\n            return [\n                .init("actions", "Capture actions", "Region, window, display, OCR, color and recording tools."),\n                .init("recording", "Recording controls", "Recording state, countdown and audio controls."),\n                .init("recent", "Recent capture", "Latest capture and source metadata."),\n                .init("preview", "Preview", "Recent capture preview and Quick Look actions."),\n                .init("ocr", "OCR text", "Recognized text plus detected links, emails and numbers."),\n                .init("codes", "QR / barcodes", "Decoded QR and barcode payloads."),\n                .init("color", "Color sample", "HEX, RGB and HSL color values."),\n                .init("measurement", "Measurement", "Pixel distance, dimensions and coordinates."),\n                .init("destination", "Destination", "Capture destination and export settings."),\n                .init("history", "Capture history", "Searchable recent capture history."),\n                .init("export", "Export actions", "Copy, pin, annotate, reveal and export."),\n                .init("status", "Capture status", "Current Capture service state and errors.")\n            ]'''
if old not in s: raise SystemExit('capture descriptor anchor missing')
s = s.replace(old, new, 1)
s = s.replace('case .capture: value.maxItems = 4', 'case .capture: value.maxItems = 12', 1)
s = s.replace('case .capture: return ["actions", "result", "progress", "resultActions", "status", "hint"]',
              'case .capture: return ["actions", "recording", "recent", "preview", "ocr", "codes", "color", "measurement", "destination", "history", "export", "status"]', 1)
p.write_text(s)
