import AppKit
import Combine
import EventKit
import IOKit.ps
import CoreAudio
import Carbon
import UserNotifications

@MainActor
final class CalendarService: ObservableObject {
    @Published var events: [EKEvent] = []
    @Published var status = "Calendar access is off. Enable it to show today's schedule."
    private let store = EKEventStore()
    private var observer: AnyCancellable?
    init() {
        observer = NotificationCenter.default.publisher(for: .EKEventStoreChanged)
            .receive(on: RunLoop.main).sink { [weak self] _ in self?.refresh() }
    }
    func requestAccess() {
        let completion: (Bool, Error?) -> Void = { [weak self] allowed, error in
            Task { @MainActor in
                self?.status = allowed ? "Calendar connected" : (error?.localizedDescription ?? "Access denied. Change it in System Settings → Privacy & Security → Calendars.")
                self?.refresh()
            }
        }
        if #available(macOS 14.0, *) { store.requestFullAccessToEvents(completion: completion) }
        else { store.requestAccess(to: .event, completion: completion) }
    }
    func refresh() {
        let authorization = EKEventStore.authorizationStatus(for: .event)
        var allowed = authorization == .authorized
        if #available(macOS 14.0, *) { allowed = allowed || authorization == .fullAccess }
        guard allowed else { events = []; return }
        let start = Calendar.current.startOfDay(for: Date())
        let end = Calendar.current.date(byAdding: .day, value: 1, to: start)!
        events = store.events(matching: store.predicateForEvents(withStart: start, end: end, calendars: nil))
            .filter { $0.endDate > Date() }.sorted { $0.startDate < $1.startDate }
        status = events.isEmpty ? "No more events today" : "Today's schedule"
    }
    func meetingURL(for event: EKEvent) -> URL? {
        let candidates = [event.url?.absoluteString, event.location, event.notes].compactMap { $0 }.joined(separator: " ")
        guard let detector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue) else { return nil }
        return detector.matches(in: candidates, range: NSRange(candidates.startIndex..., in: candidates)).compactMap(\.url).first {
            guard $0.scheme == "https", let host = $0.host?.lowercased() else { return false }
            return ["zoom.us", "meet.google.com", "teams.microsoft.com", "teams.live.com"].contains { host == $0 || host.hasSuffix("." + $0) }
        }
    }
}

struct ClipboardEntry: Identifiable { let id = UUID(); let text: String; let date = Date() }
@MainActor
final class ClipboardService: ObservableObject {
    @Published var entries: [ClipboardEntry] = []
    private var change = NSPasteboard.general.changeCount
    func reset() { entries = []; change = NSPasteboard.general.changeCount }
    func poll(enabled: Bool, excluded: String) {
        let board = NSPasteboard.general
        guard board.changeCount != change else { return }
        change = board.changeCount
        guard enabled else { return }
        let exclusions = Set(excluded.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) })
        guard !exclusions.contains(NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "") else { return }
        let sensitive = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !sensitive.contains(where: { board.types?.contains(NSPasteboard.PasteboardType($0)) == true }),
              let text = board.string(forType: .string), !text.isEmpty, text.utf8.count < 100_000 else { return }
        entries.removeAll { $0.text == text }
        entries.insert(ClipboardEntry(text: text), at: 0)
        entries = Array(entries.prefix(50))
    }
    func copy(_ entry: ClipboardEntry) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(entry.text, forType: .string)
        change = NSPasteboard.general.changeCount
    }
}

@MainActor
final class SystemService: ObservableObject {
    @Published var battery: Int?
    @Published var charging = false
    @Published var onBattery = false
    @Published var memory = ""
    @Published var storage = ""
    @Published var uptime = ""
    @Published var lowPower = false
    func refresh() {
        lowPower = ProcessInfo.processInfo.isLowPowerModeEnabled
        uptime = "\(Int(ProcessInfo.processInfo.systemUptime / 3600))h uptime"
        memory = ByteCountFormatter.string(fromByteCount: Int64(ProcessInfo.processInfo.physicalMemory), countStyle: .memory) + " installed"
        if let values = try? URL(fileURLWithPath: NSHomeDirectory()).resourceValues(forKeys: [.volumeAvailableCapacityForImportantUsageKey]),
           let free = values.volumeAvailableCapacityForImportantUsage {
            storage = ByteCountFormatter.string(fromByteCount: free, countStyle: .file) + " free"
        }
        battery = nil; charging = false; onBattery = false
        guard let snapshot = IOPSCopyPowerSourcesInfo()?.takeRetainedValue(),
              let sources = IOPSCopyPowerSourcesList(snapshot)?.takeRetainedValue() as? [CFTypeRef] else { return }
        for source in sources {
            guard let info = IOPSGetPowerSourceDescription(snapshot, source)?.takeUnretainedValue() as? [String: Any],
                  let current = info[kIOPSCurrentCapacityKey] as? Int,
                  let max = info[kIOPSMaxCapacityKey] as? Int, max > 0 else { continue }
            battery = Int(Double(current) / Double(max) * 100)
            charging = (info[kIOPSIsChargingKey] as? Bool) ?? false
            onBattery = (info[kIOPSPowerSourceStateKey] as? String) == kIOPSBatteryPowerValue
            break
        }
    }
}

struct AudioDevice: Identifiable { let id: AudioDeviceID; let name: String }
@MainActor
final class AudioService: ObservableObject {
    @Published var devices: [AudioDevice] = []
    @Published var selected: AudioDeviceID = 0
    @Published var volume: Float32 = 0
    @Published var canSetVolume = false
    @Published var error: String?
    func refresh() {
        var address = AudioObjectPropertyAddress(mSelector: kAudioHardwarePropertyDevices, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
        var size: UInt32 = 0
        guard AudioObjectGetPropertyDataSize(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size) == noErr else { return }
        var ids = [AudioDeviceID](repeating: 0, count: Int(size) / MemoryLayout<AudioDeviceID>.size)
        guard AudioObjectGetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size, &ids) == noErr else { return }
        devices = ids.compactMap { id in
            var stream = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyStreams, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
            var streamSize: UInt32 = 0
            guard AudioObjectGetPropertyDataSize(id, &stream, 0, nil, &streamSize) == noErr, streamSize > 0 else { return nil }
            var nameAddress = AudioObjectPropertyAddress(mSelector: kAudioObjectPropertyName, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
            var name: CFString = "Audio output" as CFString
            var nameSize = UInt32(MemoryLayout<CFString>.size)
            guard AudioObjectGetPropertyData(id, &nameAddress, 0, nil, &nameSize, &name) == noErr else { return nil }
            return AudioDevice(id: id, name: name as String)
        }
        address.mSelector = kAudioHardwarePropertyDefaultOutputDevice
        size = UInt32(MemoryLayout<AudioDeviceID>.size)
        _ = AudioObjectGetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size, &selected)
        var volumeAddress = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyVolumeScalar, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
        var writable: DarwinBoolean = false
        canSetVolume = AudioObjectIsPropertySettable(selected, &volumeAddress, &writable) == noErr && writable.boolValue
        size = UInt32(MemoryLayout<Float32>.size)
        if AudioObjectGetPropertyData(selected, &volumeAddress, 0, nil, &size, &volume) != noErr { canSetVolume = false }
    }
    func setOutput(_ id: AudioDeviceID) {
        var value = id
        var address = AudioObjectPropertyAddress(mSelector: kAudioHardwarePropertyDefaultOutputDevice, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
        if AudioObjectSetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, UInt32(MemoryLayout<AudioDeviceID>.size), &value) != noErr { error = "Could not change audio output." }
        refresh()
    }
    func setVolume(_ value: Float32) {
        guard canSetVolume else { return }
        var clamped = min(1, max(0, value))
        var address = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyVolumeScalar, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
        if AudioObjectSetPropertyData(selected, &address, 0, nil, UInt32(MemoryLayout<Float32>.size), &clamped) == noErr { volume = clamped }
        else { error = "This output doesn't allow software volume control." }
    }
}

@MainActor
final class MediaService: ObservableObject {
    @Published var title = "Connect a player"
    @Published var artist = "Apple Music or Spotify"
    @Published var error: String?
    @Published var busy = false
    @Published var isPlaying = false
    private var connectedApp: String?
    private var generation = 0
    func disconnect() {
        generation += 1; connectedApp = nil; isPlaying = false
        title = "Connect a player"; artist = "Apple Music or Spotify"
    }
    func poll(app: String) {
        guard connectedApp == app else { return }
        perform("refresh", app: app)
    }
    private let queue = DispatchQueue(label: "Halo.Media.AppleEvents")
    func perform(_ command: String, app: String) {
        guard ["com.apple.Music", "com.spotify.client"].contains(app),
              ["refresh", "playpause", "next track", "previous track"].contains(command), !busy else { return }
        guard NSRunningApplication.runningApplications(withBundleIdentifier: app).first != nil else {
            error = "Open the selected music player first."; isPlaying = false; connectedApp = nil; return
        }
        busy = true
        let requestGeneration = generation
        queue.async { [weak self] in
            let action = command == "refresh" ? "" : command
            let source = """
            with timeout of 5 seconds
                tell application id "\(app)"
                    \(action)
                    if player state is stopped then return {"Nothing playing", "", false}
                    return {name of current track, artist of current track, (player state is playing)}
                end tell
            end timeout
            """
            var failure: NSDictionary?
            let result = NSAppleScript(source: source)?.executeAndReturnError(&failure)
            let title = result?.atIndex(1)?.stringValue
            let artist = result?.atIndex(2)?.stringValue
            let playing = result?.atIndex(3)?.booleanValue ?? false
            let message = failure?[NSAppleScript.errorMessage] as? String
            Task { @MainActor in
                guard let self else { return }
                self.busy = false
                guard self.generation == requestGeneration else { return }
                self.error = message
                if let title, message == nil {
                    if self.title != title { self.title = title }
                    if self.artist != (artist ?? "") { self.artist = artist ?? "" }
                    if self.isPlaying != playing { self.isPlaying = playing }
                    self.connectedApp = app
                } else { self.connectedApp = nil; self.isPlaying = false }
            }
        }
    }
}

@MainActor
final class HotkeyService {
    private var hotkey: EventHotKeyRef?
    private var handler: EventHandlerRef?
    func register(code: UInt32, modifiers: UInt32) -> Bool {
        stop()
        var type = EventTypeSpec(eventClass: OSType(kEventClassKeyboard), eventKind: UInt32(kEventHotKeyPressed))
        let status = InstallEventHandler(GetApplicationEventTarget(), { _, _, _ in
            DispatchQueue.main.async { NotificationCenter.default.post(name: .init("HaloToggle"), object: nil) }
            return noErr
        }, 1, &type, nil, &handler)
        guard status == noErr else { return false }
        let identifier = EventHotKeyID(signature: 0x48414C4F, id: 1)
        return RegisterEventHotKey(code, modifiers, identifier, GetApplicationEventTarget(), 0, &hotkey) == noErr
    }
    func stop() {
        if let hotkey { UnregisterEventHotKey(hotkey) }; hotkey = nil
        if let handler { RemoveEventHandler(handler) }; handler = nil
    }
}
