import AppKit
import Combine
import EventKit
import IOKit.ps
import CoreAudio
import Carbon
import UserNotifications
import ImageIO
import Darwin

@MainActor
final class CalendarService: ObservableObject {
    @Published var events: [EKEvent] = []
    @Published var status = "Calendar access is off. Enable it to show today's schedule."
    private let store = EKEventStore()
    private var observer: AnyCancellable?
    init() {
        observer = NotificationCenter.default.publisher(for: .EKEventStoreChanged)
            .receive(on: RunLoop.main).sink { [weak self] _ in self?.refresh() }
    }
    func requestAccess() {
        let completion: (Bool, Error?) -> Void = { [weak self] allowed, error in
            Task { @MainActor in
                self?.status = allowed ? "Calendar connected" : (error?.localizedDescription ?? "Access denied. Change it in System Settings → Privacy & Security → Calendars.")
                self?.refresh()
            }
        }
        if #available(macOS 14.0, *) { store.requestFullAccessToEvents(completion: completion) }
        else { store.requestAccess(to: .event, completion: completion) }
    }
    func refresh() {
        let authorization = EKEventStore.authorizationStatus(for: .event)
        var allowed = authorization == .authorized
        if #available(macOS 14.0, *) { allowed = allowed || authorization == .fullAccess }
        guard allowed else { events = []; return }
        let start = Calendar.current.startOfDay(for: Date())
        let end = Calendar.current.date(byAdding: .day, value: 1, to: start)!
        events = store.events(matching: store.predicateForEvents(withStart: start, end: end, calendars: nil))
            .filter { $0.endDate > Date() }.sorted { $0.startDate < $1.startDate }
        status = events.isEmpty ? "No more events today" : "Today's schedule"
    }
    func meetingURL(for event: EKEvent) -> URL? {
        let candidates = [event.url?.absoluteString, event.location, event.notes].compactMap { $0 }.joined(separator: " ")
        guard let detector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue) else { return nil }
        return detector.matches(in: candidates, range: NSRange(candidates.startIndex..., in: candidates)).compactMap(\.url).first {
            guard $0.scheme == "https", let host = $0.host?.lowercased() else { return false }
            return ["zoom.us", "meet.google.com", "teams.microsoft.com", "teams.live.com"].contains { host == $0 || host.hasSuffix("." + $0) }
        }
    }
}

struct ClipboardEntry: Identifiable { let id = UUID(); let text: String; let date = Date() }
@MainActor
final class ClipboardService: ObservableObject {
    @Published var entries: [ClipboardEntry] = []
    private var change = NSPasteboard.general.changeCount
    func reset() { entries = []; change = NSPasteboard.general.changeCount }
    func poll(enabled: Bool, excluded: String) {
        let board = NSPasteboard.general
        guard board.changeCount != change else { return }
        change = board.changeCount
        guard enabled else { return }
        let exclusions = Set(excluded.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) })
        guard !exclusions.contains(NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "") else { return }
        let sensitive = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !sensitive.contains(where: { board.types?.contains(NSPasteboard.PasteboardType($0)) == true }),
              let text = board.string(forType: .string), !text.isEmpty, text.utf8.count < 100_000 else { return }
        entries.removeAll { $0.text == text }
        entries.insert(ClipboardEntry(text: text), at: 0)
        entries = Array(entries.prefix(50))
    }
    func copy(_ entry: ClipboardEntry) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(entry.text, forType: .string)
        change = NSPasteboard.general.changeCount
    }
}

@MainActor
final class SystemService: ObservableObject {
    @Published var battery: Int?
    @Published var charging = false
    @Published var onBattery = false
    @Published var memory = ""
    @Published var storage = ""
    @Published var uptime = ""
    @Published var lowPower = false

    // Detailed monitor values are sampled only while the normal opened notch is visible.
    @Published var cpuUsage = 0.0
    @Published var memoryUsage = 0.0
    @Published var swapUsage = 0.0
    @Published var diskUsage = 0.0
    @Published var networkDownPerSecond = 0.0
    @Published var networkUpPerSecond = 0.0
    @Published var thermalState = "Nominal"
    @Published var cpuHistory: [Double] = []
    @Published var memoryHistory: [Double] = []
    @Published var networkHistory: [Double] = []
    // Display brightness is intentionally nil on machines where Halo cannot safely control it.
    @Published var brightness: Double?

    private struct CPUTicks {
        var user: UInt64; var system: UInt64; var idle: UInt64; var nice: UInt64
        var total: UInt64 { user + system + idle + nice }
        var active: UInt64 { user + system + nice }
    }
    private var previousCPUTicks: CPUTicks?
    private var previousNetworkBytes: (down: UInt64, up: UInt64, date: Date)?
    private var refreshing = false

    func refresh(detailed: Bool = false) {
        guard !refreshing else { return }
        refreshing = true
        let previousCPU = previousCPUTicks
        let previousNetwork = previousNetworkBytes
        DispatchQueue.global(qos: .utility).async { [weak self] in
            let lowPower = ProcessInfo.processInfo.isLowPowerModeEnabled
            let uptime = "\(Int(ProcessInfo.processInfo.systemUptime / 3600))h uptime"
            let physicalMemory = ProcessInfo.processInfo.physicalMemory
            let memoryLabel = ByteCountFormatter.string(fromByteCount: Int64(physicalMemory), countStyle: .memory) + " installed"
            let home = URL(fileURLWithPath: NSHomeDirectory())
            let resource = try? home.resourceValues(forKeys: [.volumeAvailableCapacityForImportantUsageKey, .volumeTotalCapacityKey])
            let free = resource?.volumeAvailableCapacityForImportantUsage
            let totalDisk = resource?.volumeTotalCapacity.map(Int64.init)
            let storageLabel = free.map { ByteCountFormatter.string(fromByteCount: $0, countStyle: .file) + " free" } ?? ""

            var battery: Int?, charging = false, onBattery = false
            if let snapshot = IOPSCopyPowerSourcesInfo()?.takeRetainedValue(),
               let sources = IOPSCopyPowerSourcesList(snapshot)?.takeRetainedValue() as? [CFTypeRef] {
                for source in sources {
                    guard let info = IOPSGetPowerSourceDescription(snapshot, source)?.takeUnretainedValue() as? [String: Any],
                          let current = info[kIOPSCurrentCapacityKey] as? Int,
                          let maximum = info[kIOPSMaxCapacityKey] as? Int, maximum > 0 else { continue }
                    battery = Int(Double(current) / Double(maximum) * 100)
                    charging = (info[kIOPSIsChargingKey] as? Bool) ?? false
                    onBattery = (info[kIOPSPowerSourceStateKey] as? String) == kIOPSBatteryPowerValue
                    break
                }
            }

            let ticks = detailed ? Self.cpuTicks() : nil
            let cpuPercent: Double = {
                guard let ticks, let old = previousCPU else { return 0 }
                let totalDelta = ticks.total >= old.total ? ticks.total - old.total : 0
                let activeDelta = ticks.active >= old.active ? ticks.active - old.active : 0
                guard totalDelta > 0 else { return 0 }
                return min(100, max(0, Double(activeDelta) / Double(totalDelta) * 100))
            }()
            let memoryPercent = detailed ? Self.memoryPercent(physical: physicalMemory) : 0
            let swapPercent = detailed ? Self.swapPercent() : 0
            let diskPercent: Double = {
                guard detailed, let free, let totalDisk, totalDisk > 0 else { return 0 }
                return min(100, max(0, (1 - Double(free) / Double(totalDisk)) * 100))
            }()
            let network = detailed ? Self.networkBytes() : (0, 0)
            let now = Date()
            let rates: (Double, Double) = {
                guard detailed, let old = previousNetwork else { return (0, 0) }
                let elapsed = max(0.2, now.timeIntervalSince(old.date))
                let down = network.0 >= old.down ? Double(network.0 - old.down) / elapsed : 0
                let up = network.1 >= old.up ? Double(network.1 - old.up) / elapsed : 0
                return (down, up)
            }()
            let thermal = detailed ? Self.thermalDescription(ProcessInfo.processInfo.thermalState) : "Nominal"
            let power = (battery, charging, onBattery)

            Task { @MainActor in
                guard let self else { return }
                self.refreshing = false
                if self.lowPower != lowPower { self.lowPower = lowPower }
                if self.uptime != uptime { self.uptime = uptime }
                if self.memory != memoryLabel { self.memory = memoryLabel }
                if self.storage != storageLabel { self.storage = storageLabel }
                if self.battery != power.0 { self.battery = power.0 }
                if self.charging != power.1 { self.charging = power.1 }
                if self.onBattery != power.2 { self.onBattery = power.2 }
                guard detailed else { return }
                if let ticks { self.previousCPUTicks = ticks }
                self.previousNetworkBytes = (network.0, network.1, now)
                self.cpuUsage = cpuPercent
                self.memoryUsage = memoryPercent
                self.swapUsage = swapPercent
                self.diskUsage = diskPercent
                self.networkDownPerSecond = rates.0
                self.networkUpPerSecond = rates.1
                self.thermalState = thermal
                Self.append(cpuPercent, to: &self.cpuHistory)
                Self.append(memoryPercent, to: &self.memoryHistory)
                Self.append(min(100, (rates.0 + rates.1) / 1_000_000 * 10), to: &self.networkHistory)
            }
        }
    }

    // Brightness remains hidden when the current display does not expose a safe software control.
    func setBrightness(_ value: Double) { _ = value }

    private static func append(_ value: Double, to history: inout [Double]) {
        history.append(value)
        if history.count > 60 { history.removeFirst(history.count - 60) }
    }

    private static func cpuTicks() -> CPUTicks? {
        var info = host_cpu_load_info_data_t()
        var count = mach_msg_type_number_t(MemoryLayout<host_cpu_load_info_data_t>.stride / MemoryLayout<integer_t>.stride)
        let result = withUnsafeMutablePointer(to: &info) { pointer in
            pointer.withMemoryRebound(to: integer_t.self, capacity: Int(count)) { host_statistics(mach_host_self(), HOST_CPU_LOAD_INFO, $0, &count) }
        }
        guard result == KERN_SUCCESS else { return nil }
        return CPUTicks(user: UInt64(info.cpu_ticks.0), system: UInt64(info.cpu_ticks.1), idle: UInt64(info.cpu_ticks.2), nice: UInt64(info.cpu_ticks.3))
    }

    private static func memoryPercent(physical: UInt64) -> Double {
        var info = vm_statistics64_data_t()
        var count = mach_msg_type_number_t(MemoryLayout<vm_statistics64_data_t>.stride / MemoryLayout<integer_t>.stride)
        let result = withUnsafeMutablePointer(to: &info) { pointer in
            pointer.withMemoryRebound(to: integer_t.self, capacity: Int(count)) { host_statistics64(mach_host_self(), HOST_VM_INFO64, $0, &count) }
        }
        guard result == KERN_SUCCESS, physical > 0 else { return 0 }
        var pageSize: vm_size_t = 0
        host_page_size(mach_host_self(), &pageSize)
        let usedPages = UInt64(info.active_count) + UInt64(info.inactive_count) + UInt64(info.wire_count) + UInt64(info.compressor_page_count)
        return min(100, Double(usedPages * UInt64(pageSize)) / Double(physical) * 100)
    }

    private static func swapPercent() -> Double {
        var usage = xsw_usage()
        var size = MemoryLayout<xsw_usage>.stride
        guard sysctlbyname("vm.swapusage", &usage, &size, nil, 0) == 0, usage.xsu_total > 0 else { return 0 }
        return min(100, Double(usage.xsu_used) / Double(usage.xsu_total) * 100)
    }

    private static func networkBytes() -> (UInt64, UInt64) {
        var pointer: UnsafeMutablePointer<ifaddrs>?
        guard getifaddrs(&pointer) == 0, let first = pointer else { return (0, 0) }
        defer { freeifaddrs(pointer) }
        var down: UInt64 = 0, up: UInt64 = 0
        var current: UnsafeMutablePointer<ifaddrs>? = first
        while let node = current {
            let flags = Int32(node.pointee.ifa_flags)
            if (flags & IFF_LOOPBACK) == 0, let raw = node.pointee.ifa_data {
                let data = raw.assumingMemoryBound(to: if_data.self).pointee
                down += UInt64(data.ifi_ibytes); up += UInt64(data.ifi_obytes)
            }
            current = node.pointee.ifa_next
        }
        return (down, up)
    }

    private static func thermalDescription(_ state: ProcessInfo.ThermalState) -> String {
        switch state { case .nominal: return "Nominal"; case .fair: return "Fair"; case .serious: return "Serious"; case .critical: return "Critical"; @unknown default: return "Unknown" }
    }
}

struct AudioDevice: Identifiable { let id: AudioDeviceID; let name: String }
@MainActor
final class AudioService: ObservableObject {
    @Published var devices: [AudioDevice] = []
    @Published var selected: AudioDeviceID = 0
    @Published var volume: Float32 = 0
    @Published var canSetVolume = false
    @Published var error: String?
    func refresh() {
        var address = AudioObjectPropertyAddress(mSelector: kAudioHardwarePropertyDevices, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
        var size: UInt32 = 0
        guard AudioObjectGetPropertyDataSize(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size) == noErr else { return }
        var ids = [AudioDeviceID](repeating: 0, count: Int(size) / MemoryLayout<AudioDeviceID>.size)
        guard AudioObjectGetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size, &ids) == noErr else { return }
        devices = ids.compactMap { id in
            var stream = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyStreams, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
            var streamSize: UInt32 = 0
            guard AudioObjectGetPropertyDataSize(id, &stream, 0, nil, &streamSize) == noErr, streamSize > 0 else { return nil }
            var nameAddress = AudioObjectPropertyAddress(mSelector: kAudioObjectPropertyName, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
            var name: CFString = "Audio output" as CFString
            var nameSize = UInt32(MemoryLayout<CFString>.size)
            guard AudioObjectGetPropertyData(id, &nameAddress, 0, nil, &nameSize, &name) == noErr else { return nil }
            return AudioDevice(id: id, name: name as String)
        }
        address.mSelector = kAudioHardwarePropertyDefaultOutputDevice
        size = UInt32(MemoryLayout<AudioDeviceID>.size)
        _ = AudioObjectGetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size, &selected)
        var volumeAddress = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyVolumeScalar, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
        var writable: DarwinBoolean = false
        canSetVolume = AudioObjectIsPropertySettable(selected, &volumeAddress, &writable) == noErr && writable.boolValue
        size = UInt32(MemoryLayout<Float32>.size)
        if AudioObjectGetPropertyData(selected, &volumeAddress, 0, nil, &size, &volume) != noErr { canSetVolume = false }
    }
    func setOutput(_ id: AudioDeviceID) {
        var value = id
        var address = AudioObjectPropertyAddress(mSelector: kAudioHardwarePropertyDefaultOutputDevice, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
        if AudioObjectSetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, UInt32(MemoryLayout<AudioDeviceID>.size), &value) != noErr { error = "Could not change audio output." }
        refresh()
    }
    func setVolume(_ value: Float32) {
        guard canSetVolume else { return }
        var clamped = min(1, max(0, value))
        var address = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyVolumeScalar, mScope: kAudioObjectPropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
        if AudioObjectSetPropertyData(selected, &address, 0, nil, UInt32(MemoryLayout<Float32>.size), &clamped) == noErr { volume = clamped }
        else { error = "This output doesn't allow software volume control." }
    }
}

@MainActor
final class MediaService: ObservableObject {
    @Published var title = "Connect a player"
    @Published var artist = "Apple Music or Spotify"
    @Published var error: String?
    @Published var busy = false
    @Published var isPlaying = false
    @Published private(set) var artworkColors: [WidgetColor] = []
    @Published private(set) var artworkImage: NSImage?
    @Published private(set) var album = ""
    @Published private(set) var duration = 0.0
    @Published private(set) var position = 0.0
    @Published private(set) var shuffleSupported = false
    @Published private(set) var shuffleEnabled = false
    @Published private(set) var repeatSupported = false
    @Published private(set) var repeatMode = ""
    private var openedDetailEnabled = false
    private var artworkEnabled = false
    private var trackID = ""
    private var artworkKey = ""
    private var artworkTask: Task<Void, Never>?
    func setArtworkEnabled(_ enabled: Bool) {
        guard artworkEnabled != enabled else { return }
        artworkEnabled = enabled
        artworkTask?.cancel(); artworkKey = ""; artworkColors = []
        if enabled, let app = connectedApp { requestArtwork(app: app) }
    }
    @Published private(set) var connectedApp: String?
    private var detecting = false
    private var automaticMode = true
    private var deniedApps = Set<String>()
    private var generation = 0
    func disconnect() {
        generation += 1; connectedApp = nil; isPlaying = false
        artworkTask?.cancel(); artworkKey = ""; trackID = ""; artworkColors = []; artworkImage = nil
        album = ""; duration = 0; position = 0; shuffleSupported = false; shuffleEnabled = false; repeatSupported = false; repeatMode = ""
        title = "Connect a player"; artist = "Apple Music or Spotify"
    }
    private let queue = DispatchQueue(label: "Halo.Media.AppleEvents", qos: .utility)
    func retryDetection(preferred: String) {
        deniedApps.removeAll()
        poll(app: preferred, automatic: automaticMode)
    }
    func setOpenedDetailEnabled(_ enabled: Bool) {
        guard openedDetailEnabled != enabled else { return }
        openedDetailEnabled = enabled
        if enabled, let app = connectedApp { refreshPlaybackDetails(app: app) }
    }
    func poll(app: String, automatic: Bool = true) {
        automaticMode = automatic
        guard !detecting, !busy else { return }
        let supported = automatic ? ["com.apple.Music", "com.spotify.client"] : [app]
        let candidates = supported.filter { !deniedApps.contains($0) && !NSRunningApplication.runningApplications(withBundleIdentifier: $0).isEmpty }
        guard !candidates.isEmpty else {
            if isPlaying || connectedApp != nil { disconnect() }
            return
        }
        detecting = true
        let expectedGeneration = generation
        queue.async { [weak self] in
            let results = candidates.map { MediaProbe.read(app: $0) }
            Task { @MainActor in
                guard let self else { return }
                self.detecting = false
                guard self.generation == expectedGeneration else { return }
                for result in results where result.denied { self.deniedApps.insert(result.app) }
                let snapshots = results.compactMap(\.snapshot)
                if let selected = PlayerSelection.choose(snapshots, current: self.connectedApp, preferred: app) {
                    self.accept(selected)
                } else if self.connectedApp != nil || self.isPlaying { self.disconnect() }
                if snapshots.isEmpty, let message = results.compactMap(\.error).first, self.error != message { self.error = message }
            }
        }
    }
    private func accept(_ snapshot: PlayerSnapshot) {
        if connectedApp != snapshot.app {
            artworkTask?.cancel(); artworkKey = ""; artworkColors = []
            connectedApp = snapshot.app
        }
        if title != snapshot.title { title = snapshot.title }
        if artist != snapshot.artist { artist = snapshot.artist }
        if isPlaying != snapshot.playing { isPlaying = snapshot.playing }
        if error != nil { error = nil }
        trackID = snapshot.trackID
        requestArtwork(app: snapshot.app)
        if openedDetailEnabled { refreshPlaybackDetails(app: snapshot.app) }
    }
    func perform(_ command: String, app preferred: String) {
        let app = command == "refresh" ? preferred : (connectedApp ?? preferred)
        guard ["com.apple.Music", "com.spotify.client"].contains(app),
              ["refresh", "playpause", "next track", "previous track"].contains(command), !busy else { return }
        guard !NSRunningApplication.runningApplications(withBundleIdentifier: app).isEmpty else {
            error = "Open Apple Music or Spotify to play music."; return
        }
        deniedApps.remove(app)
        generation += 1 // Ignore an older automatic probe completing behind this command.
        artworkTask?.cancel(); artworkKey = ""
        let expectedGeneration = generation
        busy = true
        queue.async { [weak self] in
            let result = MediaProbe.read(app: app, command: command)
            Task { @MainActor in
                guard let self else { return }
                self.busy = false
                guard self.generation == expectedGeneration else { return }
                if let snapshot = result.snapshot { self.accept(snapshot) }
                else {
                    if result.denied { self.deniedApps.insert(app) }
                    self.error = result.error
                }
            }
        }
    }
    func seek(to seconds: Double) {
        guard openedDetailEnabled, let app = connectedApp, duration > 0 else { return }
        let target = min(duration, max(0, seconds))
        queue.async { [weak self] in
            let source = """
            if application id "\(app)" is running then
                tell application id "\(app)" to set player position to \(target)
            end if
            """
            var failure: NSDictionary?
            _ = NSAppleScript(source: source)?.executeAndReturnError(&failure)
            Task { @MainActor in if failure == nil { self?.position = target } }
        }
    }

    func toggleShuffle() {
        guard openedDetailEnabled, shuffleSupported, let app = connectedApp else { return }
        queue.async { [weak self] in
            let command = app == "com.apple.Music" ? "set shuffle enabled to not shuffle enabled" : "set shuffling to not shuffling"
            let source = "if application id \"\(app)\" is running then tell application id \"\(app)\" to \(command)"
            var failure: NSDictionary?
            _ = NSAppleScript(source: source)?.executeAndReturnError(&failure)
            Task { @MainActor in if failure == nil { self?.refreshPlaybackDetails(app: app) } }
        }
    }

    func cycleRepeat() {
        guard openedDetailEnabled, repeatSupported, let app = connectedApp else { return }
        queue.async { [weak self] in
            let command: String
            if app == "com.apple.Music" {
                command = "if song repeat is off then set song repeat to all else if song repeat is all then set song repeat to one else set song repeat to off"
            } else {
                command = "set repeating to not repeating"
            }
            let source = "if application id \"\(app)\" is running then tell application id \"\(app)\" to \(command)"
            var failure: NSDictionary?
            _ = NSAppleScript(source: source)?.executeAndReturnError(&failure)
            Task { @MainActor in if failure == nil { self?.refreshPlaybackDetails(app: app) } }
        }
    }

    private func refreshPlaybackDetails(app: String) {
        guard openedDetailEnabled else { return }
        let expectedGeneration = generation
        queue.async { [weak self] in
            let shuffleRead = app == "com.apple.Music" ? "shuffle enabled" : "shuffling"
            let repeatRead = app == "com.apple.Music" ? "song repeat as text" : "repeating as text"
            let source = """
            if application id "\(app)" is not running then return {"", 0, 0, false, false, false, ""}
            with timeout of 3 seconds
                tell application id "\(app)"
                    set albumName to ""
                    set durationValue to 0
                    set positionValue to 0
                    set shuffleAvailable to false
                    set shuffleValue to false
                    set repeatAvailable to false
                    set repeatValue to ""
                    try
                        set albumName to album of current track
                    end try
                    try
                        set durationValue to duration of current track
                        set positionValue to player position
                    end try
                    try
                        set shuffleValue to \(shuffleRead)
                        set shuffleAvailable to true
                    end try
                    try
                        set repeatValue to \(repeatRead)
                        set repeatAvailable to true
                    end try
                    return {albumName, durationValue, positionValue, shuffleAvailable, shuffleValue, repeatAvailable, repeatValue}
                end tell
            end timeout
            """
            var failure: NSDictionary?
            let result = NSAppleScript(source: source)?.executeAndReturnError(&failure)
            guard failure == nil, let result else { return }
            let album = result.atIndex(1)?.stringValue ?? ""
            var duration = result.atIndex(2)?.doubleValue ?? 0
            let position = result.atIndex(3)?.doubleValue ?? 0
            // Spotify exposes duration in milliseconds; Apple Music exposes seconds.
            if app == "com.spotify.client", duration > 10_000 { duration /= 1000 }
            let shuffleSupported = result.atIndex(4)?.booleanValue ?? false
            let shuffleEnabled = result.atIndex(5)?.booleanValue ?? false
            let repeatSupported = result.atIndex(6)?.booleanValue ?? false
            let repeatMode = result.atIndex(7)?.stringValue ?? ""
            Task { @MainActor in
                guard let self, self.openedDetailEnabled, self.generation == expectedGeneration, self.connectedApp == app else { return }
                self.album = album; self.duration = max(0, duration); self.position = min(max(0, position), max(0, duration))
                self.shuffleSupported = shuffleSupported; self.shuffleEnabled = shuffleEnabled
                self.repeatSupported = repeatSupported; self.repeatMode = repeatMode
            }
        }
    }

    private func requestArtwork(app: String) {
        let key = app + ":" + trackID
        guard artworkEnabled, key != artworkKey else { return }
        artworkTask?.cancel(); artworkKey = key; artworkColors = []
        guard !trackID.isEmpty else { return }
        let expectedID = trackID
        let expectedGeneration = generation
        // A separate query runs only on track changes, never for every playback poll.
        queue.async { [weak self] in
            let artwork = app == "com.spotify.client" ? "artwork url of current track" : "raw data of artwork 1 of current track"
            let source = """
            if application id "\(app)" is not running then return {"", ""}
            with timeout of 5 seconds
                tell application id "\(app)"
                    return {(id of current track as text), \(artwork)}
                end tell
            end timeout
            """
            var failure: NSDictionary?
            let result = NSAppleScript(source: source)?.executeAndReturnError(&failure)
            let returnedID = result?.atIndex(1)?.stringValue
            let urlString = app == "com.spotify.client" ? result?.atIndex(2)?.stringValue : nil
            let bytes = app == "com.apple.Music" ? result?.atIndex(2)?.data : nil
            Task { @MainActor in
                guard let self, self.artworkEnabled, self.generation == expectedGeneration,
                      self.artworkKey == key, returnedID == expectedID else { return }
                self.artworkTask = Task { [weak self] in
                    async let colorsValue = ArtworkReader.palette(data: bytes, urlString: urlString)
                    async let imageValue = ArtworkReader.image(data: bytes, urlString: urlString)
                    let (colors, image) = await (colorsValue, imageValue)
                    guard !Task.isCancelled, let self, self.artworkEnabled,
                          self.generation == expectedGeneration, self.artworkKey == key else { return }
                    self.artworkColors = colors
                    self.artworkImage = image
                }
            }
        }
    }
}

private struct MediaProbe {
    var app: String
    var snapshot: PlayerSnapshot?
    var error: String?
    var denied = false
    static func read(app: String, command: String = "refresh") -> MediaProbe {
        let action = command == "refresh" ? "" : command
        let source = """
        if application id "\(app)" is not running then return {"Nothing playing", "", false, ""}
        with timeout of 3 seconds
            tell application id "\(app)"
                \(action)
                if player state is stopped then return {"Nothing playing", "", false, ""}
                set trackKey to ""
                set trackTitle to "Playing audio"
                set trackArtist to ""
                try
                    set trackKey to (id of current track as text)
                    set trackTitle to name of current track
                    set trackArtist to artist of current track
                end try
                return {trackTitle, trackArtist, (player state is playing), trackKey}
            end tell
        end timeout
        """
        var failure: NSDictionary?
        let result = NSAppleScript(source: source)?.executeAndReturnError(&failure)
        if let failure {
            let denied = (failure[NSAppleScript.errorNumber] as? NSNumber)?.intValue == -1743
            return MediaProbe(app: app, error: failure[NSAppleScript.errorMessage] as? String ?? "Player unavailable", denied: denied)
        }
        guard let title = result?.atIndex(1)?.stringValue else { return MediaProbe(app: app) }
        return MediaProbe(app: app, snapshot: PlayerSnapshot(app: app, title: title,
            artist: result?.atIndex(2)?.stringValue ?? "", playing: result?.atIndex(3)?.booleanValue ?? false,
            trackID: result?.atIndex(4)?.stringValue ?? ""))
    }
}

/// Bounded network reads and small image samples; no artwork decoding in view bodies.
private enum ArtworkReader {
    static func image(data: Data?, urlString: String?) async -> NSImage? {
        var imageData = data
        if imageData == nil, let urlString, let url = URL(string: urlString), url.scheme == "https" {
            do {
                let request = URLRequest(url: url, cachePolicy: .returnCacheDataElseLoad, timeoutInterval: 8)
                let (downloaded, response) = try await URLSession.shared.data(for: request)
                guard let http = response as? HTTPURLResponse, http.statusCode == 200, downloaded.count <= 5_000_000 else { return nil }
                imageData = downloaded
            } catch { return nil }
        }
        guard !Task.isCancelled, let imageData, imageData.count <= 5_000_000 else { return nil }
        return NSImage(data: imageData)
    }
    static func palette(data: Data?, urlString: String?) async -> [WidgetColor] {
        var imageData = data
        if let urlString, let url = URL(string: urlString), url.scheme == "https" {
            do {
                let request = URLRequest(url: url, cachePolicy: .returnCacheDataElseLoad, timeoutInterval: 8)
                let (bytes, response) = try await URLSession.shared.bytes(for: request)
                guard let http = response as? HTTPURLResponse, http.statusCode == 200,
                      response.expectedContentLength <= 5_000_000 else { return [] }
                var received = Data()
                for try await byte in bytes {
                    try Task.checkCancellation()
                    guard received.count < 5_000_000 else { return [] }
                    received.append(byte)
                }
                imageData = received
            } catch { return [] }
        }
        guard !Task.isCancelled, let imageData, imageData.count <= 5_000_000 else { return [] }
        return await Task.detached(priority: .utility) { extract(imageData) }.value
    }
    static func extract(_ data: Data) -> [WidgetColor] {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let image = CGImageSourceCreateThumbnailAtIndex(source, 0, [
                kCGImageSourceCreateThumbnailFromImageAlways: true,
                kCGImageSourceThumbnailMaxPixelSize: 40,
                kCGImageSourceCreateThumbnailWithTransform: true
              ] as CFDictionary) else { return [] }
        var pixels = [UInt8](repeating: 0, count: 40 * 40 * 4)
        let samples: [WidgetColor] = pixels.withUnsafeMutableBytes { buffer in
            guard let context = CGContext(data: buffer.baseAddress, width: 40, height: 40, bitsPerComponent: 8,
                bytesPerRow: 160, space: CGColorSpaceCreateDeviceRGB(),
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue | CGBitmapInfo.byteOrder32Big.rawValue) else { return [] }
            context.draw(image, in: CGRect(x: 0, y: 0, width: 40, height: 40))
            let values = buffer.bindMemory(to: UInt8.self)
            return stride(from: 0, to: values.count, by: 4).compactMap { index in
                guard values[index + 3] > 200 else { return nil }
                return WidgetColor(red: Double(values[index]) / 255, green: Double(values[index + 1]) / 255, blue: Double(values[index + 2]) / 255)
            }
        }
        return MusicPalette.colors(from: samples)
    }
}

final class HotkeyService {
    private var hotkey: EventHotKeyRef?
    private var handler: EventHandlerRef?
    private let identifierID: UInt32
    private let notificationName: Notification.Name

    init(identifierID: UInt32 = 1, notificationName: Notification.Name = .init("HaloToggle")) {
        self.identifierID = identifierID
        self.notificationName = notificationName
    }

    func register(code: UInt32, modifiers: UInt32) -> Bool {
        stop()
        var type = EventTypeSpec(eventClass: OSType(kEventClassKeyboard), eventKind: UInt32(kEventHotKeyPressed))
        let userData = Unmanaged.passUnretained(self).toOpaque()
        let status = InstallEventHandler(GetApplicationEventTarget(), { _, event, userData in
            guard let event, let userData else { return OSStatus(eventNotHandledErr) }
            let service = Unmanaged<HotkeyService>.fromOpaque(userData).takeUnretainedValue()
            var identifier = EventHotKeyID()
            var actualSize = 0
            let read = GetEventParameter(event,
                                         EventParamName(kEventParamDirectObject),
                                         EventParamType(typeEventHotKeyID),
                                         nil,
                                         MemoryLayout<EventHotKeyID>.size,
                                         &actualSize,
                                         &identifier)
            // Multiple Halo shortcuts install handlers on the same application event target.
            // Returning noErr for somebody else's ID swallows the event before the owner sees it.
            guard read == noErr else { return OSStatus(eventNotHandledErr) }
            guard identifier.signature == 0x48414C4F, identifier.id == service.identifierID else {
                return OSStatus(eventNotHandledErr)
            }
            let name = service.notificationName
            DispatchQueue.main.async { NotificationCenter.default.post(name: name, object: nil) }
            return noErr
        }, 1, &type, userData, &handler)
        guard status == noErr else { return false }
        let identifier = EventHotKeyID(signature: 0x48414C4F, id: identifierID)
        let registered = RegisterEventHotKey(code, modifiers, identifier, GetApplicationEventTarget(), 0, &hotkey) == noErr
        if !registered { stop() }
        return registered
    }

    func stop() {
        if let hotkey { UnregisterEventHotKey(hotkey) }; hotkey = nil
        if let handler { RemoveEventHandler(handler) }; handler = nil
    }
}