import AppKit
import Combine
import EventKit
import IOKit.ps
import CoreAudio
import Carbon
import UserNotifications
import ImageIO

@MainActor
final class CalendarService: ObservableObject {
    @Published var events: [EKEvent] = []
    @Published var status = "Calendar access is off. Enable it to show today's schedule."
    private let store = EKEventStore()
    private var observer: AnyCancellable?
    init() {
        observer = NotificationCenter.default.publisher(for: .EKEventStoreChanged)
            .receive(on: RunLoop.main).sink { [weak self] _ in self?.refresh() }
    }
    func requestAccess() {
        let completion: (Bool, Error?) -> Void = { [weak self] allowed, error in
            Task { @MainActor in
                self?.status = allowed ? "Calendar connected" : (error?.localizedDescription ?? "Access denied. Change it in System Settings → Privacy & Security → Calendars.")
                self?.refresh()
            }
        }
        if #available(macOS 14.0, *) { store.requestFullAccessToEvents(completion: completion) }
        else { store.requestAccess(to: .event, completion: completion) }
    }
    func refresh() {
        let authorization = EKEventStore.authorizationStatus(for: .event)
        var allowed = authorization == .authorized
        if #available(macOS 14.0, *) { allowed = allowed || authorization == .fullAccess }
        guard allowed else { events = []; return }
        let start = Calendar.current.startOfDay(for: Date())
        let end = Calendar.current.date(byAdding: .day, value: 1, to: start)!
        events = store.events(matching: store.predicateForEvents(withStart: start, end: end, calendars: nil))
            .filter { $0.endDate > Date() }.sorted { $0.startDate < $1.startDate }
        status = events.isEmpty ? "No more events today" : "Today's schedule"
    }
    func meetingURL(for event: EKEvent) -> URL? {
        let candidates = [event.url?.absoluteString, event.location, event.notes].compactMap { $0 }.joined(separator: " ")
        guard let detector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue) else { return nil }
        return detector.matches(in: candidates, range: NSRange(candidates.startIndex..., in: candidates)).compactMap(\.url).first {
            guard $0.scheme == "https", let host = $0.host?.lowercased() else { return false }
            return ["zoom.us", "meet.google.com", "teams.microsoft.com", "teams.live.com"].contains { host == $0 || host.hasSuffix("." + $0) }
        }
    }
}

struct ClipboardEntry: Identifiable { let id = UUID(); let text: String; let date = Date() }
@MainActor
final class ClipboardService: ObservableObject {
    @Published var entries: [ClipboardEntry] = []
    private var change = NSPasteboard.general.changeCount
    func reset() { entries = []; change = NSPasteboard.general.changeCount }
    func poll(enabled: Bool, excluded: String) {
        let board = NSPasteboard.general
        guard board.changeCount != change else { return }
        change = board.changeCount
        guard enabled else { return }
        let exclusions = Set(excluded.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) })
        guard !exclusions.contains(NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "") else { return }
        let sensitive = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !sensitive.contains(where: { board.types?.contains(NSPasteboard.PasteboardType($0)) == true }),
              let text = board.string(forType: .string), !text.isEmpty, text.utf8.count < 100_000 else { return }
        entries.removeAll { $0.text == text }
        entries.insert(ClipboardEntry(text: text), at: 0)
        entries = Array(entries.prefix(50))
    }
    func copy(_ entry: ClipboardEntry) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(entry.text, forType: .string)
        change = NSPasteboard.general.changeCount
    }
}

@MainActor
final class SystemService: ObservableObject {
    @Published var battery: Int?
    @Published var charging = false
    @Published var onBattery = false
    @Published var memory = ""
    @Published var storage = ""
    @Published var uptime = ""
    @Published var lowPower = false
    private var refreshing = false
    func refresh() {
        guard !refreshing else { return }; refreshing = true
        DispatchQueue.global(qos: .utility).async { [weak self] in
            let lowPower = ProcessInfo.processInfo.isLowPowerModeEnabled
            let uptime = "\(Int(ProcessInfo.processInfo.systemUptime / 3600))h uptime"
            let memory = ByteCountFormatter.string(fromByteCount: Int64(ProcessInfo.processInfo.physicalMemory), countStyle: .memory) + " installed"
            let free = try? URL(fileURLWithPath: NSHomeDirectory()).resourceValues(forKeys: [.volumeAvailableCapacityForImportantUsageKey]).volumeAvailableCapacityForImportantUsage
            let storage = free.map { ByteCountFormatter.string(fromByteCount: $0, countStyle: .file) + " free" } ?? ""
            var battery: Int?, charging = false, onBattery = false
            if let snapshot = IOPSCopyPowerSourcesInfo()?.takeRetainedValue(),
               let sources = IOPSCopyPowerSourcesList(snapshot)?.takeRetainedValue() as? [CFTypeRef] {
                for source in sources {
                    guard let info = IOPSGetPowerSourceDescription(snapshot, source)?.takeUnretainedValue() as? [String: Any],
                          let current = info[kIOPSCurrentCapacityKey] as? Int,
                          let maximum = info[kIOPSMaxCapacityKey] as? Int, maximum > 0 else { continue }
                    battery = Int(Double(current) / Double(maximum) * 100)
                    charging = (info[kIOPSIsChargingKey] as? Bool) ?? false
                    onBattery = (info[kIOPSPowerSourceStateKey] as? String) == kIOPSBatteryPowerValue
                    break
                }
            }
            let power = (battery, charging, onBattery)
            Task { @MainActor in
                guard let self else { return }; self.refreshing = false
                if self.lowPower != lowPower { self.lowPower = lowPower }
                if self.uptime != uptime { self.uptime = uptime }
                if self.memory != memory { self.memory = memory }
                if self.storage != storage { self.storage = storage }
                if self.battery != power.0 { self.battery = power.0 }
                if self.charging != power.1 { self.charging = power.1 }
                if self.onBattery != power.2 { self.onBattery = power.2 }
            }
        }
    }
}

struct AudioDevice: Identifiable { let id: AudioDeviceID; let name: String }
@MainActor
final class AudioService: ObservableObject {
    @Published var devices: [AudioDevice] = []
    @Published var selected: AudioDeviceID = 0
    @Published var volume: Float32 = 0
    @Published var canSetVolume = false
    @Published var error: String?
    func refresh() {
        var address = AudioObjectPropertyAddress(mSelector: kAudioHardwarePropertyDevices, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
        var size: UInt32 = 0
        guard AudioObjectGetPropertyDataSize(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size) == noErr else { return }
        var ids = [AudioDeviceID](repeating: 0, count: Int(size) / MemoryLayout<AudioDeviceID>.size)
        guard AudioObjectGetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size, &ids) == noErr else { return }
        devices = ids.compactMap { id in
            var stream = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyStreams, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
            var streamSize: UInt32 = 0
            guard AudioObjectGetPropertyDataSize(id, &stream, 0, nil, &streamSize) == noErr, streamSize > 0 else { return nil }
            var nameAddress = AudioObjectPropertyAddress(mSelector: kAudioObjectPropertyName, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
            var name: CFString = "Audio output" as CFString
            var nameSize = UInt32(MemoryLayout<CFString>.size)
            guard AudioObjectGetPropertyData(id, &nameAddress, 0, nil, &nameSize, &name) == noErr else { return nil }
            return AudioDevice(id: id, name: name as String)
        }
        address.mSelector = kAudioHardwarePropertyDefaultOutputDevice
        size = UInt32(MemoryLayout<AudioDeviceID>.size)
        _ = AudioObjectGetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size, &selected)
        var volumeAddress = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyVolumeScalar, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
        var writable: DarwinBoolean = false
        canSetVolume = AudioObjectIsPropertySettable(selected, &volumeAddress, &writable) == noErr && writable.boolValue
        size = UInt32(MemoryLayout<Float32>.size)
        if AudioObjectGetPropertyData(selected, &volumeAddress, 0, nil, &size, &volume) != noErr { canSetVolume = false }
    }
    func setOutput(_ id: AudioDeviceID) {
        var value = id
        var address = AudioObjectPropertyAddress(mSelector: kAudioHardwarePropertyDefaultOutputDevice, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
        if AudioObjectSetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, UInt32(MemoryLayout<AudioDeviceID>.size), &value) != noErr { error = "Could not change audio output." }
        refresh()
    }
    func setVolume(_ value: Float32) {
        guard canSetVolume else { return }
        var clamped = min(1, max(0, value))
        var address = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyVolumeScalar, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
        if AudioObjectSetPropertyData(selected, &address, 0, nil, UInt32(MemoryLayout<Float32>.size), &clamped) == noErr { volume = clamped }
        else { error = "This output doesn't allow software volume control." }
    }
}

@MainActor
final class MediaService: ObservableObject {
    @Published var title = "Connect a player"
    @Published var artist = "Apple Music or Spotify"
    @Published var error: String?
    @Published var busy = false
    @Published var isPlaying = false
    @Published private(set) var artworkColors: [WidgetColor] = []
    private var artworkEnabled = false
    private var trackID = ""
    private var artworkKey = ""
    private var artworkTask: Task<Void, Never>?
    func setArtworkEnabled(_ enabled: Bool) {
        guard artworkEnabled != enabled else { return }
        artworkEnabled = enabled
        artworkTask?.cancel(); artworkKey = ""; artworkColors = []
        if enabled, let app = connectedApp { requestArtwork(app: app) }
    }
    @Published private(set) var connectedApp: String?
    private var detecting = false
    private var automaticMode = true
    private var deniedApps = Set<String>()
    private var generation = 0
    func disconnect() {
        generation += 1; connectedApp = nil; isPlaying = false
        artworkTask?.cancel(); artworkKey = ""; trackID = ""; artworkColors = []
        title = "Connect a player"; artist = "Apple Music or Spotify"
    }
    func applyDemoSnapshot(title: String, artist: String, playing: Bool) {
        generation += 1
        artworkTask?.cancel()
        connectedApp = "com.apple.Music"
        self.title = title
        self.artist = artist
        self.isPlaying = playing
        error = nil
        trackID = "halo-demo-track"
        artworkKey = "halo-demo-track"
        artworkColors = [
            WidgetColor(red: 0.42, green: 0.28, blue: 0.98),
            WidgetColor(red: 0.95, green: 0.28, blue: 0.62),
            WidgetColor(red: 0.18, green: 0.72, blue: 0.94)
        ]
    }
    private let queue = DispatchQueue(label: "Halo.Media.AppleEvents", qos: .utility)
    func retryDetection(preferred: String) {
        deniedApps.removeAll()
        poll(app: preferred, automatic: automaticMode)
    }
    func poll(app: String, automatic: Bool = true) {
        automaticMode = automatic
        guard !detecting, !busy else { return }
        let supported = automatic ? ["com.apple.Music", "com.spotify.client"] : [app]
        let candidates = supported.filter { !deniedApps.contains($0) && !NSRunningApplication.runningApplications(withBundleIdentifier: $0).isEmpty }
        guard !candidates.isEmpty else {
            if isPlaying || connectedApp != nil { disconnect() }
            return
        }
        detecting = true
        let expectedGeneration = generation
        queue.async { [weak self] in
            let results = candidates.map { MediaProbe.read(app: $0) }
            Task { @MainActor in
                guard let self else { return }
                self.detecting = false
                guard self.generation == expectedGeneration else { return }
                for result in results where result.denied { self.deniedApps.insert(result.app) }
                let snapshots = results.compactMap(\.snapshot)
                if let selected = PlayerSelection.choose(snapshots, current: self.connectedApp, preferred: app) {
                    self.accept(selected)
                } else if self.connectedApp != nil || self.isPlaying { self.disconnect() }
                if snapshots.isEmpty, let message = results.compactMap(\.error).first, self.error != message { self.error = message }
            }
        }
    }
    private func accept(_ snapshot: PlayerSnapshot) {
        if connectedApp != snapshot.app {
            artworkTask?.cancel(); artworkKey = ""; artworkColors = []
            connectedApp = snapshot.app
        }
        if title != snapshot.title { title = snapshot.title }
        if artist != snapshot.artist { artist = snapshot.artist }
        if isPlaying != snapshot.playing { isPlaying = snapshot.playing }
        if error != nil { error = nil }
        trackID = snapshot.trackID
        requestArtwork(app: snapshot.app)
    }
    func perform(_ command: String, app preferred: String) {
        if DemoMarketingStudio.shared.isEnabled {
            DemoMarketingStudio.shared.handleMediaCommand(command, media: self)
            return
        }
        let app = command == "refresh" ? preferred : (connectedApp ?? preferred)
        guard ["com.apple.Music", "com.spotify.client"].contains(app),
              ["refresh", "playpause", "next track", "previous track"].contains(command), !busy else { return }
        guard !NSRunningApplication.runningApplications(withBundleIdentifier: app).isEmpty else {
            error = "Open Apple Music or Spotify to play music."; return
        }
        deniedApps.remove(app)
        generation += 1
        artworkTask?.cancel(); artworkKey = ""
        let expectedGeneration = generation
        busy = true
        queue.async { [weak self] in
            let result = MediaProbe.read(app: app, command: command)
            Task { @MainActor in
                guard let self else { return }
                self.busy = false
                guard self.generation == expectedGeneration else { return }
                if let snapshot = result.snapshot { self.accept(snapshot) }
                else {
                    if result.denied { self.deniedApps.insert(app) }
                    self.error = result.error
                }
            }
        }
    }
    private func requestArtwork(app: String) {
        let key = app + ":" + trackID
        guard artworkEnabled, key != artworkKey else { return }
        artworkTask?.cancel(); artworkKey = key; artworkColors = []
        guard !trackID.isEmpty else { return }
        let expectedID = trackID
        let expectedGeneration = generation
        queue.async { [weak self] in
            let artwork = app == "com.spotify.client" ? "artwork url of current track" : "raw data of artwork 1 of current track"
            let source = """
            if application id "\(app)" is not running then return {"", ""}
            with timeout of 5 seconds
                tell application id "\(app)"
                    return {(id of current track as text), \(artwork)}
                end tell
            end timeout
            """
            var failure: NSDictionary?
            let result = NSAppleScript(source: source)?.executeAndReturnError(&failure)
            let returnedID = result?.atIndex(1)?.stringValue
            let urlString = app == "com.spotify.client" ? result?.atIndex(2)?.stringValue : nil
            let bytes = app == "com.apple.Music" ? result?.atIndex(2)?.data : nil
            Task { @MainActor in
                guard let self, self.artworkEnabled, self.generation == expectedGeneration,
                      self.artworkKey == key, returnedID == expectedID else { return }
                self.artworkTask = Task { [weak self] in
                    let colors = await ArtworkReader.palette(data: bytes, urlString: urlString)
                    guard !Task.isCancelled, let self, self.artworkEnabled,
                          self.generation == expectedGeneration, self.artworkKey == key else { return }
                    self.artworkColors = colors
                }
            }
        }
    }
}

private struct MediaProbe {
    var app: String
    var snapshot: PlayerSnapshot?
    var error: String?
    var denied = false
    static func read(app: String, command: String = "refresh") -> MediaProbe {
        let action = command == "refresh" ? "" : command
        let source = """
        if application id "\(app)" is not running then return {"Nothing playing", "", false, ""}
        with timeout of 3 seconds
            tell application id "\(app)"
                \(action)
                if player state is stopped then return {"Nothing playing", "", false, ""}
                set trackKey to ""
                set trackTitle to "Playing audio"
                set trackArtist to ""
                try
                    set trackKey to (id of current track as text)
                    set trackTitle to name of current track
                    set trackArtist to artist of current track
                end try
                return {trackTitle, trackArtist, (player state is playing), trackKey}
            end tell
        end timeout
        """
        var failure: NSDictionary?
        let result = NSAppleScript(source: source)?.executeAndReturnError(&failure)
        if let failure {
            let denied = (failure[NSAppleScript.errorNumber] as? NSNumber)?.intValue == -1743
            return MediaProbe(app: app, error: failure[NSAppleScript.errorMessage] as? String ?? "Player unavailable", denied: denied)
        }
        guard let title = result?.atIndex(1)?.stringValue else { return MediaProbe(app: app) }
        return MediaProbe(app: app, snapshot: PlayerSnapshot(app: app, title: title,
            artist: result?.atIndex(2)?.stringValue ?? "", playing: result?.atIndex(3)?.booleanValue ?? false,
            trackID: result?.atIndex(4)?.stringValue ?? ""))
    }
}

private enum ArtworkReader {
    static func palette(data: Data?, urlString: String?) async -> [WidgetColor] {
        var imageData = data
        if let urlString, let url = URL(string: urlString), url.scheme == "https" {
            do {
                let request = URLRequest(url: url, cachePolicy: .returnCacheDataElseLoad, timeoutInterval: 8)
                let (bytes, response) = try await URLSession.shared.bytes(for: request)
                guard let http = response as? HTTPURLResponse, http.statusCode == 200,
                      response.expectedContentLength <= 5_000_000 else { return [] }
                var received = Data()
                for try await byte in bytes {
                    try Task.checkCancellation()
                    guard received.count < 5_000_000 else { return [] }
                    received.append(byte)
                }
                imageData = received
            } catch { return [] }
        }
        guard !Task.isCancelled, let imageData, imageData.count <= 5_000_000 else { return [] }
        return await Task.detached(priority: .utility) { extract(imageData) }.value
    }
    static func extract(_ data: Data) -> [WidgetColor] {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let image = CGImageSourceCreateThumbnailAtIndex(source, 0, [
                kCGImageSourceCreateThumbnailFromImageAlways: true,
                kCGImageSourceThumbnailMaxPixelSize: 40,
                kCGImageSourceCreateThumbnailWithTransform: true
              ] as CFDictionary) else { return [] }
        var pixels = [UInt8](repeating: 0, count: 40 * 40 * 4)
        let samples: [WidgetColor] = pixels.withUnsafeMutableBytes { buffer in
            guard let context = CGContext(data: buffer.baseAddress, width: 40, height: 40, bitsPerComponent: 8,
                bytesPerRow: 160, space: CGColorSpaceCreateDeviceRGB(),
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue | CGBitmapInfo.byteOrder32Big.rawValue) else { return [] }
            context.draw(image, in: CGRect(x: 0, y: 0, width: 40, height: 40))
            let values = buffer.bindMemory(to: UInt8.self)
            return stride(from: 0, to: values.count, by: 4).compactMap { index in
                guard values[index + 3] > 200 else { return nil }
                return WidgetColor(red: Double(values[index]) / 255, green: Double(values[index + 1]) / 255, blue: Double(values[index + 2]) / 255)
            }
        }
        return MusicPalette.colors(from: samples)
    }
}

@MainActor
final class HotkeyService {
    private var hotkey: EventHotKeyRef?
    private var handler: EventHandlerRef?
    func register(code: UInt32, modifiers: UInt32) -> Bool {
        stop()
        var type = EventTypeSpec(eventClass: OSType(kEventClassKeyboard), eventKind: UInt32(kEventHotKeyPressed))
        let status = InstallEventHandler(GetApplicationEventTarget(), { _, _, _ in
            DispatchQueue.main.async { NotificationCenter.default.post(name: .init("HaloToggle"), object: nil) }
            return noErr
        }, 1, &type, nil, &handler)
        guard status == noErr else { return false }
        let identifier = EventHotKeyID(signature: 0x48414C4F, id: 1)
        return RegisterEventHotKey(code, modifiers, identifier, GetApplicationEventTarget(), 0, &hotkey) == noErr
    }
    func stop() {
        if let hotkey { UnregisterEventHotKey(hotkey) }; hotkey = nil
        if let handler { RemoveEventHandler(handler) }; handler = nil
    }
}