from pathlib import Path


def replace_once(path: str, old: str, new: str):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f'marker not found in {path}: {old[:120]!r}')
    p.write_text(text.replace(old, new, 1))

# 1) Extend per-widget model with additive, backward-compatible presentation options.
replace_once(
    'Halo/Core/WidgetModels.swift',
    '''enum WidgetFontFamily: String, Codable, CaseIterable { case system, rounded, serif, monospaced, custom }\nenum WidgetFontWeight: String, Codable, CaseIterable { case light, regular, medium, semibold, bold }\n''',
    '''enum WidgetFontFamily: String, Codable, CaseIterable { case system, rounded, serif, monospaced, custom }\nenum WidgetFontWeight: String, Codable, CaseIterable { case light, regular, medium, semibold, bold }\n\nenum WidgetLayoutMode: String, Codable, CaseIterable, Identifiable {\n    case standard = "Standard"\n    case compact = "Compact"\n    case hero = "Hero"\n    case minimal = "Minimal"\n    case dense = "Dense"\n    var id: String { rawValue }\n}\n\nenum WidgetCardBackgroundStyle: String, Codable, CaseIterable, Identifiable {\n    case none = "None"\n    case solid = "Solid"\n    case gradient = "Gradient"\n    case glass = "Glass"\n    case accent = "Accent Tint"\n    var id: String { rawValue }\n}\n\nenum WidgetOutlineStyle: String, Codable, CaseIterable, Identifiable {\n    case none = "None"\n    case solid = "Solid"\n    case dashed = "Dashed"\n    case double = "Double"\n    case glow = "Glow"\n    var id: String { rawValue }\n}\n\nenum WidgetVisualPreset: String, CaseIterable, Identifiable {\n    case clean = "Clean"\n    case glass = "Glass"\n    case filled = "Filled"\n    case outline = "Outline"\n    case floating = "Floating"\n    case minimal = "Minimal"\n    var id: String { rawValue }\n}\n'''
)

replace_once(
    'Halo/Core/WidgetModels.swift',
    '''    var showTitle = true\n    var clock = ClockOptions()\n    var content: WidgetContentOptions?\n    var chrome: WidgetChromeOptions?\n    var resolvedContent: WidgetContentOptions { content ?? WidgetContentOptions() }\n    var resolvedChrome: WidgetChromeOptions { chrome ?? WidgetChromeOptions() }\n''',
    '''    var showTitle = true\n    var clock = ClockOptions()\n    var content: WidgetContentOptions?\n    var chrome: WidgetChromeOptions?\n\n    // Optional so profiles created before the opened-widget design system decode unchanged.\n    var layoutMode: WidgetLayoutMode?\n    var cardBackgroundStyle: WidgetCardBackgroundStyle?\n    var backgroundSecondaryColor: WidgetColor?\n    var outlineStyle: WidgetOutlineStyle?\n    var showHeaderIcon: Bool?\n    var gradientAngle: Double?\n    var glassTintOpacity: Double?\n\n    var resolvedContent: WidgetContentOptions { content ?? WidgetContentOptions() }\n    var resolvedChrome: WidgetChromeOptions { chrome ?? WidgetChromeOptions() }\n    var resolvedLayoutMode: WidgetLayoutMode { layoutMode ?? .standard }\n    var resolvedCardBackgroundStyle: WidgetCardBackgroundStyle { cardBackgroundStyle ?? .solid }\n    var resolvedBackgroundSecondaryColor: WidgetColor { backgroundSecondaryColor ?? accentColor }\n    var resolvedOutlineStyle: WidgetOutlineStyle {\n        if let outlineStyle { return outlineStyle }\n        return resolvedChrome.borderOpacity > 0 && resolvedChrome.borderWidth > 0 ? .solid : .none\n    }\n    var showsHeaderIcon: Bool { showHeaderIcon ?? true }\n    var resolvedGradientAngle: Double { min(360, max(-360, gradientAngle ?? 135)) }\n    var resolvedGlassTintOpacity: Double { min(0.6, max(0, glassTintOpacity ?? 0.10)) }\n'''
)

replace_once(
    'Halo/Core/WidgetModels.swift',
    '''        v.textColor = try textColor.validated(); v.accentColor = try accentColor.validated(); v.backgroundColor = try backgroundColor.validated()\n        v.customFont = String(customFont.prefix(120))\n        if content != nil { v.content = try resolvedContent.validated() }\n        if chrome != nil { v.chrome = try resolvedChrome.validated() }\n        return v\n''',
    '''        v.textColor = try textColor.validated(); v.accentColor = try accentColor.validated(); v.backgroundColor = try backgroundColor.validated()\n        if backgroundSecondaryColor != nil { v.backgroundSecondaryColor = try resolvedBackgroundSecondaryColor.validated() }\n        if let angle = gradientAngle {\n            guard angle.isFinite else { throw CocoaError(.fileReadCorruptFile) }\n            v.gradientAngle = min(360, max(-360, angle))\n        }\n        if let tint = glassTintOpacity {\n            guard tint.isFinite else { throw CocoaError(.fileReadCorruptFile) }\n            v.glassTintOpacity = min(0.6, max(0, tint))\n        }\n        v.customFont = String(customFont.prefix(120))\n        if content != nil { v.content = try resolvedContent.validated() }\n        if chrome != nil { v.chrome = try resolvedChrome.validated() }\n        return v\n'''
)

# 2) Render backgrounds and outline styles in WidgetCard, and make layout modes visibly distinct.
replace_once(
    'Halo/Views/WidgetViews.swift',
    '''    private var fittedStyle: WidgetStyle {\n        guard let height = availableHeight else { return style }\n        var fitted = style\n        fitted.padding = min(style.padding, max(0, height * 0.08))\n        fitted.minimumHeight = 0\n        fitted.fontSize = min(style.fontSize, max(10, height * 0.18))\n        return fitted\n    }\n''',
    '''    private var fittedStyle: WidgetStyle {\n        var fitted = style\n        switch style.resolvedLayoutMode {\n        case .standard: break\n        case .compact:\n            fitted.padding *= 0.78\n            fitted.fontSize *= 0.94\n        case .hero:\n            fitted.fontSize *= 1.10\n            fitted.padding *= 1.08\n        case .minimal:\n            fitted.padding *= 0.72\n        case .dense:\n            fitted.padding *= 0.62\n            fitted.fontSize *= 0.90\n        }\n        guard let height = availableHeight else { return fitted }\n        fitted.padding = min(fitted.padding, max(0, height * 0.08))\n        fitted.minimumHeight = 0\n        fitted.fontSize = min(fitted.fontSize, max(10, height * 0.18))\n        return fitted\n    }\n'''
)

replace_once(
    'Halo/Views/WidgetViews.swift',
    '''    private var styledContent: some View {\n        content.environment(\\.widgetStyle, fittedStyle).font(fittedStyle.font())\n            .foregroundStyle(style.textColor.color).tint(style.accentColor.color)\n            .controlSize(contentOptions.controlSize.swiftUI)\n            .opacity(chrome.contentOpacity)\n    }\n    var body: some View {\n''',
    '''    private var styledContent: some View {\n        content.environment(\\.widgetStyle, fittedStyle).font(fittedStyle.font())\n            .foregroundStyle(style.textColor.color).tint(style.accentColor.color)\n            .controlSize(contentOptions.controlSize.swiftUI)\n            .opacity(chrome.contentOpacity)\n    }\n\n    private var shape: RoundedRectangle {\n        RoundedRectangle(cornerRadius: fittedStyle.cornerRadius, style: .continuous)\n    }\n\n    @ViewBuilder private var cardBackground: some View {\n        switch fittedStyle.resolvedCardBackgroundStyle {\n        case .none:\n            Color.clear\n        case .solid:\n            shape.fill(fittedStyle.backgroundColor.color.opacity(fittedStyle.backgroundOpacity))\n        case .gradient:\n            shape.fill(\n                LinearGradient(\n                    colors: [\n                        fittedStyle.backgroundColor.color.opacity(fittedStyle.backgroundOpacity),\n                        fittedStyle.resolvedBackgroundSecondaryColor.color.opacity(fittedStyle.backgroundOpacity)\n                    ],\n                    startPoint: UnitPoint(x: 0.5 - 0.5 * cos(fittedStyle.resolvedGradientAngle * .pi / 180),\n                                          y: 0.5 - 0.5 * sin(fittedStyle.resolvedGradientAngle * .pi / 180)),\n                    endPoint: UnitPoint(x: 0.5 + 0.5 * cos(fittedStyle.resolvedGradientAngle * .pi / 180),\n                                        y: 0.5 + 0.5 * sin(fittedStyle.resolvedGradientAngle * .pi / 180))\n                )\n            )\n        case .glass:\n            shape.fill(.ultraThinMaterial)\n                .overlay(shape.fill(fittedStyle.backgroundColor.color.opacity(fittedStyle.resolvedGlassTintOpacity)))\n        case .accent:\n            shape.fill(fittedStyle.accentColor.color.opacity(fittedStyle.backgroundOpacity))\n        }\n    }\n\n    @ViewBuilder private var cardOutline: some View {\n        let color = chrome.borderColor.color.opacity(chrome.borderOpacity)\n        let width = max(0.5, chrome.borderWidth)\n        switch fittedStyle.resolvedOutlineStyle {\n        case .none:\n            EmptyView()\n        case .solid:\n            shape.stroke(color, lineWidth: width)\n        case .dashed:\n            shape.stroke(color, style: StrokeStyle(lineWidth: width, lineCap: .round, dash: [7, 5]))\n        case .double:\n            shape.stroke(color, lineWidth: width)\n                .overlay(shape.inset(by: max(3, width + 2)).stroke(color.opacity(0.70), lineWidth: max(0.5, width * 0.65)))\n        case .glow:\n            shape.stroke(color, lineWidth: width)\n                .shadow(color: chrome.borderColor.color.opacity(max(0.20, chrome.borderOpacity)), radius: max(5, width * 3))\n        }\n    }\n\n    var body: some View {\n'''
)

replace_once(
    'Halo/Views/WidgetViews.swift',
    '''        .background(style.backgroundColor.color.opacity(style.backgroundOpacity), in: RoundedRectangle(cornerRadius: style.cornerRadius, style: .continuous))\n        .overlay(\n            RoundedRectangle(cornerRadius: style.cornerRadius, style: .continuous)\n                .stroke(chrome.borderColor.color.opacity(chrome.borderOpacity), lineWidth: chrome.borderWidth)\n        )\n        .shadow(color: .black.opacity(chrome.shadowOpacity), radius: chrome.shadowRadius, y: chrome.shadowY)\n''',
    '''        .background { cardBackground }\n        .overlay { cardOutline }\n        .shadow(color: .black.opacity(chrome.shadowOpacity), radius: chrome.shadowRadius, y: chrome.shadowY)\n'''
)

# Replace clock body with layout-aware variants.
replace_once(
    'Halo/Views/WidgetViews.swift',
    '''        TimelineView(.periodic(from: start, by: style.clock.showSeconds ? 1 : 60)) { context in\n            VStack(alignment: style.resolvedContent.alignment.horizontal, spacing: max(2, min(20, style.resolvedContent.spacing * 0.55))) {\n                if style.showTitle && !compact {\n                    HStack(spacing: max(4, style.resolvedContent.spacing * 0.55)) {\n                        Image(systemName: "clock")\n                            .font(.system(size: style.resolvedContent.iconSize, weight: .semibold))\n                            .foregroundStyle(style.accentColor.color)\n                        Text("Clock").font(style.font(scale: 0.75))\n                    }\n                }\n                Text(clockFormatter.string(from: context.date)).font(style.font()).monospacedDigit()\n                if style.clock.showDate && !compact {\n                    Text(dateFormatter.string(from: context.date))\n                        .font(style.font(scale: 0.75))\n                }\n            }\n            .frame(maxWidth: .infinity, alignment: style.resolvedContent.alignment.alignment)\n        }\n''',
    '''        TimelineView(.periodic(from: start, by: style.clock.showSeconds ? 1 : 60)) { context in\n            let spacing = max(2, min(20, style.resolvedContent.spacing * 0.55))\n            Group {\n                switch style.resolvedLayoutMode {\n                case .compact:\n                    HStack(spacing: spacing) {\n                        if style.showTitle && !compact { clockHeader(scale: 0.68) }\n                        Text(clockFormatter.string(from: context.date)).font(style.font()).monospacedDigit()\n                        Spacer(minLength: 4)\n                        if style.clock.showDate && !compact {\n                            Text(dateFormatter.string(from: context.date)).font(style.font(scale: 0.68)).foregroundStyle(.secondary)\n                        }\n                    }\n                case .hero:\n                    VStack(alignment: style.resolvedContent.alignment.horizontal, spacing: spacing) {\n                        if style.showTitle && !compact { clockHeader(scale: 0.75) }\n                        Text(clockFormatter.string(from: context.date)).font(style.font(scale: 1.35)).monospacedDigit()\n                        if style.clock.showDate && !compact { Text(dateFormatter.string(from: context.date)).font(style.font(scale: 0.80)) }\n                    }\n                case .minimal:\n                    VStack(alignment: style.resolvedContent.alignment.horizontal, spacing: spacing) {\n                        Text(clockFormatter.string(from: context.date)).font(style.font()).monospacedDigit()\n                        if style.clock.showDate && !compact { Text(dateFormatter.string(from: context.date)).font(style.font(scale: 0.68)).foregroundStyle(.secondary) }\n                    }\n                case .dense, .standard:\n                    VStack(alignment: style.resolvedContent.alignment.horizontal, spacing: style.resolvedLayoutMode == .dense ? max(2, spacing * 0.55) : spacing) {\n                        if style.showTitle && !compact { clockHeader(scale: 0.75) }\n                        Text(clockFormatter.string(from: context.date)).font(style.font()).monospacedDigit()\n                        if style.clock.showDate && !compact { Text(dateFormatter.string(from: context.date)).font(style.font(scale: 0.75)) }\n                    }\n                }\n            }\n            .frame(maxWidth: .infinity, alignment: style.resolvedContent.alignment.alignment)\n        }\n    }\n\n    @ViewBuilder private func clockHeader(scale: Double) -> some View {\n        HStack(spacing: max(4, style.resolvedContent.spacing * 0.55)) {\n            if style.showsHeaderIcon {\n                Image(systemName: "clock")\n                    .font(.system(size: style.resolvedContent.iconSize, weight: .semibold))\n                    .foregroundStyle(style.accentColor.color)\n            }\n            Text("Clock").font(style.font(scale: scale))\n        }\n'''
)

# 3) Make integration widgets respond to the same layout selector and header-icon visibility.
replace_once(
    'Halo/Views/ModuleViews.swift',
    '''    var body: some View {\n        VStack(alignment: options.alignment.horizontal, spacing: options.spacing) {\n            if style.showTitle {\n                HStack(spacing: max(4, options.spacing * 0.55)) {\n                    if options.iconSize > 0 { Image(systemName: id.symbol).font(.system(size: options.iconSize, weight: .semibold)).foregroundStyle(style.accentColor.color) }\n                    Text(id.title).font(style.font())\n                }\n            }\n            content\n        }.frame(maxWidth: .infinity, alignment: options.alignment.alignment)\n    }\n''',
    '''    var body: some View {\n        Group {\n            switch style.resolvedLayoutMode {\n            case .compact:\n                HStack(alignment: .top, spacing: max(6, options.spacing)) {\n                    if style.showTitle { header(scale: 0.82) }\n                    content\n                }\n            case .hero:\n                VStack(alignment: options.alignment.horizontal, spacing: options.spacing * 1.15) {\n                    if style.showTitle { header(scale: 1.08) }\n                    content\n                }\n            case .minimal:\n                VStack(alignment: options.alignment.horizontal, spacing: max(3, options.spacing * 0.65)) {\n                    if style.showTitle { header(scale: 0.72) }\n                    content\n                }\n            case .dense:\n                VStack(alignment: options.alignment.horizontal, spacing: max(2, options.spacing * 0.55)) {\n                    if style.showTitle { header(scale: 0.78) }\n                    content\n                }\n            case .standard:\n                VStack(alignment: options.alignment.horizontal, spacing: options.spacing) {\n                    if style.showTitle { header(scale: 1) }\n                    content\n                }\n            }\n        }\n        .frame(maxWidth: .infinity, alignment: options.alignment.alignment)\n    }\n\n    @ViewBuilder private func header(scale: Double) -> some View {\n        HStack(spacing: max(4, options.spacing * 0.55)) {\n            if style.showsHeaderIcon && options.iconSize > 0 {\n                Image(systemName: id.symbol)\n                    .font(.system(size: options.iconSize, weight: .semibold))\n                    .foregroundStyle(style.accentColor.color)\n            }\n            Text(id.title).font(style.font(scale: scale))\n        }\n    }\n'''
)

# 4) Add a high-level design studio on top of the existing deep widget controls.
replace_once(
    'Halo/Views/WidgetSettingsView.swift',
    '''        Section("Opened notch widget") {\n            Text("Customize \\(selected.title) independently. These settings apply to the widget in Halo's opened dashboard and travel with profiles and display-specific layouts.")\n                .font(.caption).foregroundStyle(.secondary)\n        }\n        Section("Typography") {\n''',
    '''        Section("Opened notch widget") {\n            Text("Customize \\(selected.title) independently. These settings apply to the widget in Halo's opened dashboard and travel with profiles and display-specific layouts.")\n                .font(.caption).foregroundStyle(.secondary)\n        }\n        Section("Quick looks") {\n            LazyVGrid(columns: [GridItem(.adaptive(minimum: 92), spacing: 8)], spacing: 8) {\n                ForEach(WidgetVisualPreset.allCases) { preset in\n                    Button(preset.rawValue) { applyVisualPreset(preset) }\n                        .buttonStyle(.bordered)\n                }\n            }\n            Text("Presets are starting points. Every setting below remains editable per widget.")\n                .font(.caption).foregroundStyle(.secondary)\n        }\n        Section("Layout") {\n            Picker("Widget layout", selection: Binding(\n                get: { style.wrappedValue.resolvedLayoutMode },\n                set: { style.wrappedValue.layoutMode = $0 }\n            )) {\n                ForEach(WidgetLayoutMode.allCases) { Text($0.rawValue).tag($0) }\n            }\n            .pickerStyle(.segmented)\n            Toggle("Show header", isOn: style.showTitle)\n            if style.wrappedValue.showTitle {\n                Toggle("Show header icon", isOn: Binding(\n                    get: { style.wrappedValue.showsHeaderIcon },\n                    set: { style.wrappedValue.showHeaderIcon = $0 }\n                ))\n            }\n            Text("Compact moves the header beside content, Hero gives the widget stronger emphasis, Minimal strips it back, and Dense reduces internal spacing.")\n                .font(.caption).foregroundStyle(.secondary)\n        }\n        Section("Typography") {\n'''
)

# Remove duplicate Show title from typography.
replace_once(
    'Halo/Views/WidgetSettingsView.swift',
    '''            colorPicker("Text", style.textColor)\n            colorPicker("Accent", style.accentColor)\n            Toggle("Show title", isOn: style.showTitle)\n        }\n''',
    '''            colorPicker("Text", style.textColor)\n            colorPicker("Accent", style.accentColor)\n        }\n'''
)

# Replace top of Card section with material controls.
replace_once(
    'Halo/Views/WidgetSettingsView.swift',
    '''        Section("Card") {\n            colorPicker("Background", style.backgroundColor)\n            PreciseSlider(title: "Background opacity", value: style.backgroundOpacity, range: 0...1, step: 0.01, decimals: 2)\n            PreciseSlider(title: "Padding", value: style.padding, range: 0...32, step: 1, suffix: "pt")\n''',
    '''        Section("Card") {\n            Picker("Background", selection: Binding(\n                get: { style.wrappedValue.resolvedCardBackgroundStyle },\n                set: { style.wrappedValue.cardBackgroundStyle = $0 }\n            )) {\n                ForEach(WidgetCardBackgroundStyle.allCases) { Text($0.rawValue).tag($0) }\n            }\n            if style.wrappedValue.resolvedCardBackgroundStyle != .none {\n                colorPicker(style.wrappedValue.resolvedCardBackgroundStyle == .accent ? "Tint base" : "Background", style.backgroundColor)\n                if style.wrappedValue.resolvedCardBackgroundStyle == .gradient {\n                    ColorPicker("Second color", selection: Binding(\n                        get: { style.wrappedValue.resolvedBackgroundSecondaryColor.color },\n                        set: { style.wrappedValue.backgroundSecondaryColor = WidgetColor($0) }\n                    ), supportsOpacity: false)\n                    PreciseSlider(title: "Gradient angle", value: Binding(\n                        get: { style.wrappedValue.resolvedGradientAngle },\n                        set: { style.wrappedValue.gradientAngle = $0 }\n                    ), range: -180...180, step: 5, suffix: "°")\n                }\n                if style.wrappedValue.resolvedCardBackgroundStyle == .glass {\n                    PreciseSlider(title: "Glass tint", value: Binding(\n                        get: { style.wrappedValue.resolvedGlassTintOpacity },\n                        set: { style.wrappedValue.glassTintOpacity = $0 }\n                    ), range: 0...0.6, step: 0.02, decimals: 2)\n                }\n                PreciseSlider(title: "Background opacity", value: style.backgroundOpacity, range: 0...1, step: 0.01, decimals: 2)\n            }\n            PreciseSlider(title: "Padding", value: style.padding, range: 0...32, step: 1, suffix: "pt")\n'''
)

# Insert outline picker before border controls and conditionally show border controls.
replace_once(
    'Halo/Views/WidgetSettingsView.swift',
    '''            Divider()\n            ColorPicker("Border color", selection: Binding(get: { chrome.wrappedValue.borderColor.color }, set: { chrome.wrappedValue.borderColor = WidgetColor($0) }), supportsOpacity: false)\n            PreciseSlider(title: "Border opacity", value: chrome.borderOpacity, range: 0...1, step: 0.05, decimals: 2)\n            PreciseSlider(title: "Border width", value: chrome.borderWidth, range: 0...6, step: 0.25, suffix: "pt", decimals: 2)\n            PreciseSlider(title: "Shadow opacity", value: chrome.shadowOpacity, range: 0...0.8, step: 0.05, decimals: 2)\n''',
    '''            Divider()\n            Picker("Outline", selection: Binding(\n                get: { style.wrappedValue.resolvedOutlineStyle },\n                set: { value in\n                    style.wrappedValue.outlineStyle = value\n                    if value != .none && chrome.wrappedValue.borderWidth <= 0 { chrome.wrappedValue.borderWidth = 1 }\n                    if value != .none && chrome.wrappedValue.borderOpacity <= 0 { chrome.wrappedValue.borderOpacity = 0.35 }\n                }\n            )) {\n                ForEach(WidgetOutlineStyle.allCases) { Text($0.rawValue).tag($0) }\n            }\n            if style.wrappedValue.resolvedOutlineStyle != .none {\n                ColorPicker("Outline color", selection: Binding(get: { chrome.wrappedValue.borderColor.color }, set: { chrome.wrappedValue.borderColor = WidgetColor($0) }), supportsOpacity: false)\n                PreciseSlider(title: "Outline opacity", value: chrome.borderOpacity, range: 0...1, step: 0.05, decimals: 2)\n                PreciseSlider(title: "Outline width", value: chrome.borderWidth, range: 0...6, step: 0.25, suffix: "pt", decimals: 2)\n            }\n            PreciseSlider(title: "Shadow opacity", value: chrome.shadowOpacity, range: 0...0.8, step: 0.05, decimals: 2)\n'''
)

# Add preset method before colorPicker helper.
replace_once(
    'Halo/Views/WidgetSettingsView.swift',
    '''    private func colorPicker(_ title: String, _ value: Binding<WidgetColor>) -> some View {\n''',
    '''    private func applyVisualPreset(_ preset: WidgetVisualPreset) {\n        var value = style.wrappedValue\n        var card = value.resolvedChrome\n        switch preset {\n        case .clean:\n            value.layoutMode = .standard\n            value.cardBackgroundStyle = .solid\n            value.backgroundOpacity = 0.06\n            value.outlineStyle = .none\n            value.showHeaderIcon = true\n            card.borderOpacity = 0\n            card.borderWidth = 0\n            card.shadowOpacity = 0\n        case .glass:\n            value.layoutMode = .standard\n            value.cardBackgroundStyle = .glass\n            value.glassTintOpacity = 0.10\n            value.outlineStyle = .solid\n            card.borderOpacity = 0.16\n            card.borderWidth = 0.75\n            card.shadowOpacity = 0.16\n            card.shadowRadius = 12\n        case .filled:\n            value.layoutMode = .hero\n            value.cardBackgroundStyle = .gradient\n            value.backgroundOpacity = 0.28\n            value.backgroundSecondaryColor = value.accentColor\n            value.outlineStyle = .none\n            card.borderOpacity = 0\n            card.shadowOpacity = 0.12\n        case .outline:\n            value.layoutMode = .standard\n            value.cardBackgroundStyle = .none\n            value.outlineStyle = .solid\n            card.borderOpacity = 0.45\n            card.borderWidth = 1\n            card.shadowOpacity = 0\n        case .floating:\n            value.layoutMode = .compact\n            value.cardBackgroundStyle = .glass\n            value.outlineStyle = .glow\n            card.borderColor = value.accentColor\n            card.borderOpacity = 0.45\n            card.borderWidth = 1\n            card.shadowOpacity = 0.28\n            card.shadowRadius = 18\n            card.shadowY = 5\n        case .minimal:\n            value.layoutMode = .minimal\n            value.cardBackgroundStyle = .none\n            value.outlineStyle = .none\n            value.showHeaderIcon = false\n            value.padding = max(4, value.padding * 0.65)\n            card.borderOpacity = 0\n            card.borderWidth = 0\n            card.shadowOpacity = 0\n        }\n        value.chrome = card\n        style.wrappedValue = value\n    }\n\n    private func colorPicker(_ title: String, _ value: Binding<WidgetColor>) -> some View {\n'''
)

print('opened widget design system patch applied')
